/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileLayoutRouteImport } from './routes/profile/layout'
import { Route as AdminLayoutRouteImport } from './routes/admin/layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VoistlusedIndexRouteImport } from './routes/voistlused/index'
import { Route as UudisedIndexRouteImport } from './routes/uudised/index'
import { Route as TagasisideIndexRouteImport } from './routes/tagasiside/index'
import { Route as ReitingIndexRouteImport } from './routes/reiting/index'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as ReeglidIndexRouteImport } from './routes/reeglid/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as LitsentsIndexRouteImport } from './routes/litsents/index'
import { Route as KontaktIndexRouteImport } from './routes/kontakt/index'
import { Route as KlubidIndexRouteImport } from './routes/klubid/index'
import { Route as UudisedBlogidRouteImport } from './routes/uudised/$blogid'
import { Route as LitsentsSuccessRouteImport } from './routes/litsents/success'
import { Route as LitsentsCancelRouteImport } from './routes/litsents/cancel'
import { Route as VoistlusedTournamentidLayoutRouteImport } from './routes/voistlused/$tournamentid/layout'
import { Route as AdminTournamentsLayoutRouteImport } from './routes/admin/tournaments/layout'
import { Route as AdminDashboardLayoutRouteImport } from './routes/admin/dashboard/layout'
import { Route as AdminClubsLayoutRouteImport } from './routes/admin/clubs/layout'
import { Route as AdminBlogLayoutRouteImport } from './routes/admin/blog/layout'
import { Route as VoistlusedTournamentidIndexRouteImport } from './routes/voistlused/$tournamentid/index'
import { Route as ProfileTournamentsIndexRouteImport } from './routes/profile/tournaments/index'
import { Route as ProfileSettingsIndexRouteImport } from './routes/profile/settings/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminTournamentsIndexRouteImport } from './routes/admin/tournaments/index'
import { Route as AdminRatingIndexRouteImport } from './routes/admin/rating/index'
import { Route as AdminFeedbackIndexRouteImport } from './routes/admin/feedback/index'
import { Route as AdminDashboardIndexRouteImport } from './routes/admin/dashboard/index'
import { Route as AdminClubsIndexRouteImport } from './routes/admin/clubs/index'
import { Route as AdminBlogIndexRouteImport } from './routes/admin/blog/index'
import { Route as AdminTournamentsTournamentidLayoutRouteImport } from './routes/admin/tournaments/$tournamentid/layout'
import { Route as VoistlusedTournamentidTulemusedIndexRouteImport } from './routes/voistlused/$tournamentid/tulemused/index'
import { Route as VoistlusedTournamentidSponsoridIndexRouteImport } from './routes/voistlused/$tournamentid/sponsorid/index'
import { Route as VoistlusedTournamentidMeediaIndexRouteImport } from './routes/voistlused/$tournamentid/meedia/index'
import { Route as VoistlusedTournamentidMangudIndexRouteImport } from './routes/voistlused/$tournamentid/mangud/index'
import { Route as VoistlusedTournamentidMangijadIndexRouteImport } from './routes/voistlused/$tournamentid/mangijad/index'
import { Route as VoistlusedTournamentidLauadIndexRouteImport } from './routes/voistlused/$tournamentid/lauad/index'
import { Route as VoistlusedTournamentidKohadIndexRouteImport } from './routes/voistlused/$tournamentid/kohad/index'
import { Route as VoistlusedTournamentidJuhendIndexRouteImport } from './routes/voistlused/$tournamentid/juhend/index'
import { Route as VoistlusedTournamentidGaleriiIndexRouteImport } from './routes/voistlused/$tournamentid/galerii/index'
import { Route as VoistlusedTournamentidAjakavaIndexRouteImport } from './routes/voistlused/$tournamentid/ajakava/index'
import { Route as AdminTournamentsNewIndexRouteImport } from './routes/admin/tournaments/new/index'
import { Route as AdminTournamentsTournamentidIndexRouteImport } from './routes/admin/tournaments/$tournamentid/index'
import { Route as AdminRatingTournamentidIndexRouteImport } from './routes/admin/rating/$tournamentid/index'
import { Route as AdminBlogNewIndexRouteImport } from './routes/admin/blog/new/index'
import { Route as AdminBlogBlogidIndexRouteImport } from './routes/admin/blog/$blogid/index'
import { Route as AdminTournamentsTournamentidKohadRouteImport } from './routes/admin/tournaments/$tournamentid/kohad'
import { Route as AdminTournamentsTournamentidAjakavaLayoutRouteImport } from './routes/admin/tournaments/$tournamentid/ajakava/layout'
import { Route as VoistlusedTournamentidTulemusedGroupidIndexRouteImport } from './routes/voistlused/$tournamentid/tulemused/$groupid/index'
import { Route as AdminTournamentsTournamentidTabelidIndexRouteImport } from './routes/admin/tournaments/$tournamentid/tabelid/index'
import { Route as AdminTournamentsTournamentidPildidIndexRouteImport } from './routes/admin/tournaments/$tournamentid/pildid/index'
import { Route as AdminTournamentsTournamentidMangudIndexRouteImport } from './routes/admin/tournaments/$tournamentid/mangud/index'
import { Route as AdminTournamentsTournamentidGrupidIndexRouteImport } from './routes/admin/tournaments/$tournamentid/grupid/index'
import { Route as AdminTournamentsTournamentidAjakavaIndexRouteImport } from './routes/admin/tournaments/$tournamentid/ajakava/index'
import { Route as AdminTournamentsTournamentidGrupidGroupidLayoutRouteImport } from './routes/admin/tournaments/$tournamentid/grupid/$groupid/layout'
import { Route as AdminTournamentsTournamentidGrupidUusIndexRouteImport } from './routes/admin/tournaments/$tournamentid/grupid/uus/index'
import { Route as AdminTournamentsTournamentidGrupidGroupidIndexRouteImport } from './routes/admin/tournaments/$tournamentid/grupid/$groupid/index'
import { Route as AdminTournamentsTournamentidAjakavaSeadedIndexRouteImport } from './routes/admin/tournaments/$tournamentid/ajakava/seaded/index'
import { Route as AdminTournamentsTournamentidGrupidGroupidTabelidIndexRouteImport } from './routes/admin/tournaments/$tournamentid/grupid/$groupid/tabelid/index'
import { Route as AdminTournamentsTournamentidGrupidGroupidOsalejadIndexRouteImport } from './routes/admin/tournaments/$tournamentid/grupid/$groupid/osalejad/index'
import { Route as AdminTournamentsTournamentidGrupidGroupidMangudIndexRouteImport } from './routes/admin/tournaments/$tournamentid/grupid/$groupid/mangud/index'
import { Route as AdminTournamentsTournamentidGrupidGroupidKohadIndexRouteImport } from './routes/admin/tournaments/$tournamentid/grupid/$groupid/kohad/index'

const ProfileLayoutRoute = ProfileLayoutRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VoistlusedIndexRoute = VoistlusedIndexRouteImport.update({
  id: '/voistlused/',
  path: '/voistlused/',
  getParentRoute: () => rootRouteImport,
} as any)
const UudisedIndexRoute = UudisedIndexRouteImport.update({
  id: '/uudised/',
  path: '/uudised/',
  getParentRoute: () => rootRouteImport,
} as any)
const TagasisideIndexRoute = TagasisideIndexRouteImport.update({
  id: '/tagasiside/',
  path: '/tagasiside/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReitingIndexRoute = ReitingIndexRouteImport.update({
  id: '/reiting/',
  path: '/reiting/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReeglidIndexRoute = ReeglidIndexRouteImport.update({
  id: '/reeglid/',
  path: '/reeglid/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileLayoutRoute,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const LitsentsIndexRoute = LitsentsIndexRouteImport.update({
  id: '/litsents/',
  path: '/litsents/',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktIndexRoute = KontaktIndexRouteImport.update({
  id: '/kontakt/',
  path: '/kontakt/',
  getParentRoute: () => rootRouteImport,
} as any)
const KlubidIndexRoute = KlubidIndexRouteImport.update({
  id: '/klubid/',
  path: '/klubid/',
  getParentRoute: () => rootRouteImport,
} as any)
const UudisedBlogidRoute = UudisedBlogidRouteImport.update({
  id: '/uudised/$blogid',
  path: '/uudised/$blogid',
  getParentRoute: () => rootRouteImport,
} as any)
const LitsentsSuccessRoute = LitsentsSuccessRouteImport.update({
  id: '/litsents/success',
  path: '/litsents/success',
  getParentRoute: () => rootRouteImport,
} as any)
const LitsentsCancelRoute = LitsentsCancelRouteImport.update({
  id: '/litsents/cancel',
  path: '/litsents/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const VoistlusedTournamentidLayoutRoute =
  VoistlusedTournamentidLayoutRouteImport.update({
    id: '/voistlused/$tournamentid',
    path: '/voistlused/$tournamentid',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminTournamentsLayoutRoute = AdminTournamentsLayoutRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminDashboardLayoutRoute = AdminDashboardLayoutRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminClubsLayoutRoute = AdminClubsLayoutRouteImport.update({
  id: '/clubs',
  path: '/clubs',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminBlogLayoutRoute = AdminBlogLayoutRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const VoistlusedTournamentidIndexRoute =
  VoistlusedTournamentidIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => VoistlusedTournamentidLayoutRoute,
  } as any)
const ProfileTournamentsIndexRoute = ProfileTournamentsIndexRouteImport.update({
  id: '/tournaments/',
  path: '/tournaments/',
  getParentRoute: () => ProfileLayoutRoute,
} as any)
const ProfileSettingsIndexRoute = ProfileSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => ProfileLayoutRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminTournamentsIndexRoute = AdminTournamentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminTournamentsLayoutRoute,
} as any)
const AdminRatingIndexRoute = AdminRatingIndexRouteImport.update({
  id: '/rating/',
  path: '/rating/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminFeedbackIndexRoute = AdminFeedbackIndexRouteImport.update({
  id: '/feedback/',
  path: '/feedback/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminDashboardLayoutRoute,
} as any)
const AdminClubsIndexRoute = AdminClubsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminClubsLayoutRoute,
} as any)
const AdminBlogIndexRoute = AdminBlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminBlogLayoutRoute,
} as any)
const AdminTournamentsTournamentidLayoutRoute =
  AdminTournamentsTournamentidLayoutRouteImport.update({
    id: '/$tournamentid',
    path: '/$tournamentid',
    getParentRoute: () => AdminTournamentsLayoutRoute,
  } as any)
const VoistlusedTournamentidTulemusedIndexRoute =
  VoistlusedTournamentidTulemusedIndexRouteImport.update({
    id: '/tulemused/',
    path: '/tulemused/',
    getParentRoute: () => VoistlusedTournamentidLayoutRoute,
  } as any)
const VoistlusedTournamentidSponsoridIndexRoute =
  VoistlusedTournamentidSponsoridIndexRouteImport.update({
    id: '/sponsorid/',
    path: '/sponsorid/',
    getParentRoute: () => VoistlusedTournamentidLayoutRoute,
  } as any)
const VoistlusedTournamentidMeediaIndexRoute =
  VoistlusedTournamentidMeediaIndexRouteImport.update({
    id: '/meedia/',
    path: '/meedia/',
    getParentRoute: () => VoistlusedTournamentidLayoutRoute,
  } as any)
const VoistlusedTournamentidMangudIndexRoute =
  VoistlusedTournamentidMangudIndexRouteImport.update({
    id: '/mangud/',
    path: '/mangud/',
    getParentRoute: () => VoistlusedTournamentidLayoutRoute,
  } as any)
const VoistlusedTournamentidMangijadIndexRoute =
  VoistlusedTournamentidMangijadIndexRouteImport.update({
    id: '/mangijad/',
    path: '/mangijad/',
    getParentRoute: () => VoistlusedTournamentidLayoutRoute,
  } as any)
const VoistlusedTournamentidLauadIndexRoute =
  VoistlusedTournamentidLauadIndexRouteImport.update({
    id: '/lauad/',
    path: '/lauad/',
    getParentRoute: () => VoistlusedTournamentidLayoutRoute,
  } as any)
const VoistlusedTournamentidKohadIndexRoute =
  VoistlusedTournamentidKohadIndexRouteImport.update({
    id: '/kohad/',
    path: '/kohad/',
    getParentRoute: () => VoistlusedTournamentidLayoutRoute,
  } as any)
const VoistlusedTournamentidJuhendIndexRoute =
  VoistlusedTournamentidJuhendIndexRouteImport.update({
    id: '/juhend/',
    path: '/juhend/',
    getParentRoute: () => VoistlusedTournamentidLayoutRoute,
  } as any)
const VoistlusedTournamentidGaleriiIndexRoute =
  VoistlusedTournamentidGaleriiIndexRouteImport.update({
    id: '/galerii/',
    path: '/galerii/',
    getParentRoute: () => VoistlusedTournamentidLayoutRoute,
  } as any)
const VoistlusedTournamentidAjakavaIndexRoute =
  VoistlusedTournamentidAjakavaIndexRouteImport.update({
    id: '/ajakava/',
    path: '/ajakava/',
    getParentRoute: () => VoistlusedTournamentidLayoutRoute,
  } as any)
const AdminTournamentsNewIndexRoute =
  AdminTournamentsNewIndexRouteImport.update({
    id: '/new/',
    path: '/new/',
    getParentRoute: () => AdminTournamentsLayoutRoute,
  } as any)
const AdminTournamentsTournamentidIndexRoute =
  AdminTournamentsTournamentidIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminTournamentsTournamentidLayoutRoute,
  } as any)
const AdminRatingTournamentidIndexRoute =
  AdminRatingTournamentidIndexRouteImport.update({
    id: '/rating/$tournamentid/',
    path: '/rating/$tournamentid/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminBlogNewIndexRoute = AdminBlogNewIndexRouteImport.update({
  id: '/new/',
  path: '/new/',
  getParentRoute: () => AdminBlogLayoutRoute,
} as any)
const AdminBlogBlogidIndexRoute = AdminBlogBlogidIndexRouteImport.update({
  id: '/$blogid/',
  path: '/$blogid/',
  getParentRoute: () => AdminBlogLayoutRoute,
} as any)
const AdminTournamentsTournamentidKohadRoute =
  AdminTournamentsTournamentidKohadRouteImport.update({
    id: '/kohad',
    path: '/kohad',
    getParentRoute: () => AdminTournamentsTournamentidLayoutRoute,
  } as any)
const AdminTournamentsTournamentidAjakavaLayoutRoute =
  AdminTournamentsTournamentidAjakavaLayoutRouteImport.update({
    id: '/ajakava',
    path: '/ajakava',
    getParentRoute: () => AdminTournamentsTournamentidLayoutRoute,
  } as any)
const VoistlusedTournamentidTulemusedGroupidIndexRoute =
  VoistlusedTournamentidTulemusedGroupidIndexRouteImport.update({
    id: '/tulemused/$groupid/',
    path: '/tulemused/$groupid/',
    getParentRoute: () => VoistlusedTournamentidLayoutRoute,
  } as any)
const AdminTournamentsTournamentidTabelidIndexRoute =
  AdminTournamentsTournamentidTabelidIndexRouteImport.update({
    id: '/tabelid/',
    path: '/tabelid/',
    getParentRoute: () => AdminTournamentsTournamentidLayoutRoute,
  } as any)
const AdminTournamentsTournamentidPildidIndexRoute =
  AdminTournamentsTournamentidPildidIndexRouteImport.update({
    id: '/pildid/',
    path: '/pildid/',
    getParentRoute: () => AdminTournamentsTournamentidLayoutRoute,
  } as any)
const AdminTournamentsTournamentidMangudIndexRoute =
  AdminTournamentsTournamentidMangudIndexRouteImport.update({
    id: '/mangud/',
    path: '/mangud/',
    getParentRoute: () => AdminTournamentsTournamentidLayoutRoute,
  } as any)
const AdminTournamentsTournamentidGrupidIndexRoute =
  AdminTournamentsTournamentidGrupidIndexRouteImport.update({
    id: '/grupid/',
    path: '/grupid/',
    getParentRoute: () => AdminTournamentsTournamentidLayoutRoute,
  } as any)
const AdminTournamentsTournamentidAjakavaIndexRoute =
  AdminTournamentsTournamentidAjakavaIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminTournamentsTournamentidAjakavaLayoutRoute,
  } as any)
const AdminTournamentsTournamentidGrupidGroupidLayoutRoute =
  AdminTournamentsTournamentidGrupidGroupidLayoutRouteImport.update({
    id: '/grupid/$groupid',
    path: '/grupid/$groupid',
    getParentRoute: () => AdminTournamentsTournamentidLayoutRoute,
  } as any)
const AdminTournamentsTournamentidGrupidUusIndexRoute =
  AdminTournamentsTournamentidGrupidUusIndexRouteImport.update({
    id: '/grupid/uus/',
    path: '/grupid/uus/',
    getParentRoute: () => AdminTournamentsTournamentidLayoutRoute,
  } as any)
const AdminTournamentsTournamentidGrupidGroupidIndexRoute =
  AdminTournamentsTournamentidGrupidGroupidIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminTournamentsTournamentidGrupidGroupidLayoutRoute,
  } as any)
const AdminTournamentsTournamentidAjakavaSeadedIndexRoute =
  AdminTournamentsTournamentidAjakavaSeadedIndexRouteImport.update({
    id: '/seaded/',
    path: '/seaded/',
    getParentRoute: () => AdminTournamentsTournamentidAjakavaLayoutRoute,
  } as any)
const AdminTournamentsTournamentidGrupidGroupidTabelidIndexRoute =
  AdminTournamentsTournamentidGrupidGroupidTabelidIndexRouteImport.update({
    id: '/tabelid/',
    path: '/tabelid/',
    getParentRoute: () => AdminTournamentsTournamentidGrupidGroupidLayoutRoute,
  } as any)
const AdminTournamentsTournamentidGrupidGroupidOsalejadIndexRoute =
  AdminTournamentsTournamentidGrupidGroupidOsalejadIndexRouteImport.update({
    id: '/osalejad/',
    path: '/osalejad/',
    getParentRoute: () => AdminTournamentsTournamentidGrupidGroupidLayoutRoute,
  } as any)
const AdminTournamentsTournamentidGrupidGroupidMangudIndexRoute =
  AdminTournamentsTournamentidGrupidGroupidMangudIndexRouteImport.update({
    id: '/mangud/',
    path: '/mangud/',
    getParentRoute: () => AdminTournamentsTournamentidGrupidGroupidLayoutRoute,
  } as any)
const AdminTournamentsTournamentidGrupidGroupidKohadIndexRoute =
  AdminTournamentsTournamentidGrupidGroupidKohadIndexRouteImport.update({
    id: '/kohad/',
    path: '/kohad/',
    getParentRoute: () => AdminTournamentsTournamentidGrupidGroupidLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminLayoutRouteWithChildren
  '/profile': typeof ProfileLayoutRouteWithChildren
  '/admin/blog': typeof AdminBlogLayoutRouteWithChildren
  '/admin/clubs': typeof AdminClubsLayoutRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardLayoutRouteWithChildren
  '/admin/tournaments': typeof AdminTournamentsLayoutRouteWithChildren
  '/voistlused/$tournamentid': typeof VoistlusedTournamentidLayoutRouteWithChildren
  '/litsents/cancel': typeof LitsentsCancelRoute
  '/litsents/success': typeof LitsentsSuccessRoute
  '/uudised/$blogid': typeof UudisedBlogidRoute
  '/klubid': typeof KlubidIndexRoute
  '/kontakt': typeof KontaktIndexRoute
  '/litsents': typeof LitsentsIndexRoute
  '/login': typeof LoginIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/reeglid': typeof ReeglidIndexRoute
  '/register': typeof RegisterIndexRoute
  '/reiting': typeof ReitingIndexRoute
  '/tagasiside': typeof TagasisideIndexRoute
  '/uudised': typeof UudisedIndexRoute
  '/voistlused': typeof VoistlusedIndexRoute
  '/admin/tournaments/$tournamentid': typeof AdminTournamentsTournamentidLayoutRouteWithChildren
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/clubs/': typeof AdminClubsIndexRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/admin/feedback': typeof AdminFeedbackIndexRoute
  '/admin/rating': typeof AdminRatingIndexRoute
  '/admin/tournaments/': typeof AdminTournamentsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/profile/settings': typeof ProfileSettingsIndexRoute
  '/profile/tournaments': typeof ProfileTournamentsIndexRoute
  '/voistlused/$tournamentid/': typeof VoistlusedTournamentidIndexRoute
  '/admin/tournaments/$tournamentid/ajakava': typeof AdminTournamentsTournamentidAjakavaLayoutRouteWithChildren
  '/admin/tournaments/$tournamentid/kohad': typeof AdminTournamentsTournamentidKohadRoute
  '/admin/blog/$blogid': typeof AdminBlogBlogidIndexRoute
  '/admin/blog/new': typeof AdminBlogNewIndexRoute
  '/admin/rating/$tournamentid': typeof AdminRatingTournamentidIndexRoute
  '/admin/tournaments/$tournamentid/': typeof AdminTournamentsTournamentidIndexRoute
  '/admin/tournaments/new': typeof AdminTournamentsNewIndexRoute
  '/voistlused/$tournamentid/ajakava': typeof VoistlusedTournamentidAjakavaIndexRoute
  '/voistlused/$tournamentid/galerii': typeof VoistlusedTournamentidGaleriiIndexRoute
  '/voistlused/$tournamentid/juhend': typeof VoistlusedTournamentidJuhendIndexRoute
  '/voistlused/$tournamentid/kohad': typeof VoistlusedTournamentidKohadIndexRoute
  '/voistlused/$tournamentid/lauad': typeof VoistlusedTournamentidLauadIndexRoute
  '/voistlused/$tournamentid/mangijad': typeof VoistlusedTournamentidMangijadIndexRoute
  '/voistlused/$tournamentid/mangud': typeof VoistlusedTournamentidMangudIndexRoute
  '/voistlused/$tournamentid/meedia': typeof VoistlusedTournamentidMeediaIndexRoute
  '/voistlused/$tournamentid/sponsorid': typeof VoistlusedTournamentidSponsoridIndexRoute
  '/voistlused/$tournamentid/tulemused': typeof VoistlusedTournamentidTulemusedIndexRoute
  '/admin/tournaments/$tournamentid/grupid/$groupid': typeof AdminTournamentsTournamentidGrupidGroupidLayoutRouteWithChildren
  '/admin/tournaments/$tournamentid/ajakava/': typeof AdminTournamentsTournamentidAjakavaIndexRoute
  '/admin/tournaments/$tournamentid/grupid': typeof AdminTournamentsTournamentidGrupidIndexRoute
  '/admin/tournaments/$tournamentid/mangud': typeof AdminTournamentsTournamentidMangudIndexRoute
  '/admin/tournaments/$tournamentid/pildid': typeof AdminTournamentsTournamentidPildidIndexRoute
  '/admin/tournaments/$tournamentid/tabelid': typeof AdminTournamentsTournamentidTabelidIndexRoute
  '/voistlused/$tournamentid/tulemused/$groupid': typeof VoistlusedTournamentidTulemusedGroupidIndexRoute
  '/admin/tournaments/$tournamentid/ajakava/seaded': typeof AdminTournamentsTournamentidAjakavaSeadedIndexRoute
  '/admin/tournaments/$tournamentid/grupid/$groupid/': typeof AdminTournamentsTournamentidGrupidGroupidIndexRoute
  '/admin/tournaments/$tournamentid/grupid/uus': typeof AdminTournamentsTournamentidGrupidUusIndexRoute
  '/admin/tournaments/$tournamentid/grupid/$groupid/kohad': typeof AdminTournamentsTournamentidGrupidGroupidKohadIndexRoute
  '/admin/tournaments/$tournamentid/grupid/$groupid/mangud': typeof AdminTournamentsTournamentidGrupidGroupidMangudIndexRoute
  '/admin/tournaments/$tournamentid/grupid/$groupid/osalejad': typeof AdminTournamentsTournamentidGrupidGroupidOsalejadIndexRoute
  '/admin/tournaments/$tournamentid/grupid/$groupid/tabelid': typeof AdminTournamentsTournamentidGrupidGroupidTabelidIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminLayoutRouteWithChildren
  '/litsents/cancel': typeof LitsentsCancelRoute
  '/litsents/success': typeof LitsentsSuccessRoute
  '/uudised/$blogid': typeof UudisedBlogidRoute
  '/klubid': typeof KlubidIndexRoute
  '/kontakt': typeof KontaktIndexRoute
  '/litsents': typeof LitsentsIndexRoute
  '/login': typeof LoginIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/reeglid': typeof ReeglidIndexRoute
  '/register': typeof RegisterIndexRoute
  '/reiting': typeof ReitingIndexRoute
  '/tagasiside': typeof TagasisideIndexRoute
  '/uudised': typeof UudisedIndexRoute
  '/voistlused': typeof VoistlusedIndexRoute
  '/admin/blog': typeof AdminBlogIndexRoute
  '/admin/clubs': typeof AdminClubsIndexRoute
  '/admin/dashboard': typeof AdminDashboardIndexRoute
  '/admin/feedback': typeof AdminFeedbackIndexRoute
  '/admin/rating': typeof AdminRatingIndexRoute
  '/admin/tournaments': typeof AdminTournamentsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/profile/settings': typeof ProfileSettingsIndexRoute
  '/profile/tournaments': typeof ProfileTournamentsIndexRoute
  '/voistlused/$tournamentid': typeof VoistlusedTournamentidIndexRoute
  '/admin/tournaments/$tournamentid/kohad': typeof AdminTournamentsTournamentidKohadRoute
  '/admin/blog/$blogid': typeof AdminBlogBlogidIndexRoute
  '/admin/blog/new': typeof AdminBlogNewIndexRoute
  '/admin/rating/$tournamentid': typeof AdminRatingTournamentidIndexRoute
  '/admin/tournaments/$tournamentid': typeof AdminTournamentsTournamentidIndexRoute
  '/admin/tournaments/new': typeof AdminTournamentsNewIndexRoute
  '/voistlused/$tournamentid/ajakava': typeof VoistlusedTournamentidAjakavaIndexRoute
  '/voistlused/$tournamentid/galerii': typeof VoistlusedTournamentidGaleriiIndexRoute
  '/voistlused/$tournamentid/juhend': typeof VoistlusedTournamentidJuhendIndexRoute
  '/voistlused/$tournamentid/kohad': typeof VoistlusedTournamentidKohadIndexRoute
  '/voistlused/$tournamentid/lauad': typeof VoistlusedTournamentidLauadIndexRoute
  '/voistlused/$tournamentid/mangijad': typeof VoistlusedTournamentidMangijadIndexRoute
  '/voistlused/$tournamentid/mangud': typeof VoistlusedTournamentidMangudIndexRoute
  '/voistlused/$tournamentid/meedia': typeof VoistlusedTournamentidMeediaIndexRoute
  '/voistlused/$tournamentid/sponsorid': typeof VoistlusedTournamentidSponsoridIndexRoute
  '/voistlused/$tournamentid/tulemused': typeof VoistlusedTournamentidTulemusedIndexRoute
  '/admin/tournaments/$tournamentid/ajakava': typeof AdminTournamentsTournamentidAjakavaIndexRoute
  '/admin/tournaments/$tournamentid/grupid': typeof AdminTournamentsTournamentidGrupidIndexRoute
  '/admin/tournaments/$tournamentid/mangud': typeof AdminTournamentsTournamentidMangudIndexRoute
  '/admin/tournaments/$tournamentid/pildid': typeof AdminTournamentsTournamentidPildidIndexRoute
  '/admin/tournaments/$tournamentid/tabelid': typeof AdminTournamentsTournamentidTabelidIndexRoute
  '/voistlused/$tournamentid/tulemused/$groupid': typeof VoistlusedTournamentidTulemusedGroupidIndexRoute
  '/admin/tournaments/$tournamentid/ajakava/seaded': typeof AdminTournamentsTournamentidAjakavaSeadedIndexRoute
  '/admin/tournaments/$tournamentid/grupid/$groupid': typeof AdminTournamentsTournamentidGrupidGroupidIndexRoute
  '/admin/tournaments/$tournamentid/grupid/uus': typeof AdminTournamentsTournamentidGrupidUusIndexRoute
  '/admin/tournaments/$tournamentid/grupid/$groupid/kohad': typeof AdminTournamentsTournamentidGrupidGroupidKohadIndexRoute
  '/admin/tournaments/$tournamentid/grupid/$groupid/mangud': typeof AdminTournamentsTournamentidGrupidGroupidMangudIndexRoute
  '/admin/tournaments/$tournamentid/grupid/$groupid/osalejad': typeof AdminTournamentsTournamentidGrupidGroupidOsalejadIndexRoute
  '/admin/tournaments/$tournamentid/grupid/$groupid/tabelid': typeof AdminTournamentsTournamentidGrupidGroupidTabelidIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminLayoutRouteWithChildren
  '/profile': typeof ProfileLayoutRouteWithChildren
  '/admin/blog': typeof AdminBlogLayoutRouteWithChildren
  '/admin/clubs': typeof AdminClubsLayoutRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardLayoutRouteWithChildren
  '/admin/tournaments': typeof AdminTournamentsLayoutRouteWithChildren
  '/voistlused/$tournamentid': typeof VoistlusedTournamentidLayoutRouteWithChildren
  '/litsents/cancel': typeof LitsentsCancelRoute
  '/litsents/success': typeof LitsentsSuccessRoute
  '/uudised/$blogid': typeof UudisedBlogidRoute
  '/klubid/': typeof KlubidIndexRoute
  '/kontakt/': typeof KontaktIndexRoute
  '/litsents/': typeof LitsentsIndexRoute
  '/login/': typeof LoginIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/reeglid/': typeof ReeglidIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/reiting/': typeof ReitingIndexRoute
  '/tagasiside/': typeof TagasisideIndexRoute
  '/uudised/': typeof UudisedIndexRoute
  '/voistlused/': typeof VoistlusedIndexRoute
  '/admin/tournaments/$tournamentid': typeof AdminTournamentsTournamentidLayoutRouteWithChildren
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/clubs/': typeof AdminClubsIndexRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/admin/feedback/': typeof AdminFeedbackIndexRoute
  '/admin/rating/': typeof AdminRatingIndexRoute
  '/admin/tournaments/': typeof AdminTournamentsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/profile/settings/': typeof ProfileSettingsIndexRoute
  '/profile/tournaments/': typeof ProfileTournamentsIndexRoute
  '/voistlused/$tournamentid/': typeof VoistlusedTournamentidIndexRoute
  '/admin/tournaments/$tournamentid/ajakava': typeof AdminTournamentsTournamentidAjakavaLayoutRouteWithChildren
  '/admin/tournaments/$tournamentid/kohad': typeof AdminTournamentsTournamentidKohadRoute
  '/admin/blog/$blogid/': typeof AdminBlogBlogidIndexRoute
  '/admin/blog/new/': typeof AdminBlogNewIndexRoute
  '/admin/rating/$tournamentid/': typeof AdminRatingTournamentidIndexRoute
  '/admin/tournaments/$tournamentid/': typeof AdminTournamentsTournamentidIndexRoute
  '/admin/tournaments/new/': typeof AdminTournamentsNewIndexRoute
  '/voistlused/$tournamentid/ajakava/': typeof VoistlusedTournamentidAjakavaIndexRoute
  '/voistlused/$tournamentid/galerii/': typeof VoistlusedTournamentidGaleriiIndexRoute
  '/voistlused/$tournamentid/juhend/': typeof VoistlusedTournamentidJuhendIndexRoute
  '/voistlused/$tournamentid/kohad/': typeof VoistlusedTournamentidKohadIndexRoute
  '/voistlused/$tournamentid/lauad/': typeof VoistlusedTournamentidLauadIndexRoute
  '/voistlused/$tournamentid/mangijad/': typeof VoistlusedTournamentidMangijadIndexRoute
  '/voistlused/$tournamentid/mangud/': typeof VoistlusedTournamentidMangudIndexRoute
  '/voistlused/$tournamentid/meedia/': typeof VoistlusedTournamentidMeediaIndexRoute
  '/voistlused/$tournamentid/sponsorid/': typeof VoistlusedTournamentidSponsoridIndexRoute
  '/voistlused/$tournamentid/tulemused/': typeof VoistlusedTournamentidTulemusedIndexRoute
  '/admin/tournaments/$tournamentid/grupid/$groupid': typeof AdminTournamentsTournamentidGrupidGroupidLayoutRouteWithChildren
  '/admin/tournaments/$tournamentid/ajakava/': typeof AdminTournamentsTournamentidAjakavaIndexRoute
  '/admin/tournaments/$tournamentid/grupid/': typeof AdminTournamentsTournamentidGrupidIndexRoute
  '/admin/tournaments/$tournamentid/mangud/': typeof AdminTournamentsTournamentidMangudIndexRoute
  '/admin/tournaments/$tournamentid/pildid/': typeof AdminTournamentsTournamentidPildidIndexRoute
  '/admin/tournaments/$tournamentid/tabelid/': typeof AdminTournamentsTournamentidTabelidIndexRoute
  '/voistlused/$tournamentid/tulemused/$groupid/': typeof VoistlusedTournamentidTulemusedGroupidIndexRoute
  '/admin/tournaments/$tournamentid/ajakava/seaded/': typeof AdminTournamentsTournamentidAjakavaSeadedIndexRoute
  '/admin/tournaments/$tournamentid/grupid/$groupid/': typeof AdminTournamentsTournamentidGrupidGroupidIndexRoute
  '/admin/tournaments/$tournamentid/grupid/uus/': typeof AdminTournamentsTournamentidGrupidUusIndexRoute
  '/admin/tournaments/$tournamentid/grupid/$groupid/kohad/': typeof AdminTournamentsTournamentidGrupidGroupidKohadIndexRoute
  '/admin/tournaments/$tournamentid/grupid/$groupid/mangud/': typeof AdminTournamentsTournamentidGrupidGroupidMangudIndexRoute
  '/admin/tournaments/$tournamentid/grupid/$groupid/osalejad/': typeof AdminTournamentsTournamentidGrupidGroupidOsalejadIndexRoute
  '/admin/tournaments/$tournamentid/grupid/$groupid/tabelid/': typeof AdminTournamentsTournamentidGrupidGroupidTabelidIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/profile'
    | '/admin/blog'
    | '/admin/clubs'
    | '/admin/dashboard'
    | '/admin/tournaments'
    | '/voistlused/$tournamentid'
    | '/litsents/cancel'
    | '/litsents/success'
    | '/uudised/$blogid'
    | '/klubid'
    | '/kontakt'
    | '/litsents'
    | '/login'
    | '/profile/'
    | '/reeglid'
    | '/register'
    | '/reiting'
    | '/tagasiside'
    | '/uudised'
    | '/voistlused'
    | '/admin/tournaments/$tournamentid'
    | '/admin/blog/'
    | '/admin/clubs/'
    | '/admin/dashboard/'
    | '/admin/feedback'
    | '/admin/rating'
    | '/admin/tournaments/'
    | '/admin/users'
    | '/profile/settings'
    | '/profile/tournaments'
    | '/voistlused/$tournamentid/'
    | '/admin/tournaments/$tournamentid/ajakava'
    | '/admin/tournaments/$tournamentid/kohad'
    | '/admin/blog/$blogid'
    | '/admin/blog/new'
    | '/admin/rating/$tournamentid'
    | '/admin/tournaments/$tournamentid/'
    | '/admin/tournaments/new'
    | '/voistlused/$tournamentid/ajakava'
    | '/voistlused/$tournamentid/galerii'
    | '/voistlused/$tournamentid/juhend'
    | '/voistlused/$tournamentid/kohad'
    | '/voistlused/$tournamentid/lauad'
    | '/voistlused/$tournamentid/mangijad'
    | '/voistlused/$tournamentid/mangud'
    | '/voistlused/$tournamentid/meedia'
    | '/voistlused/$tournamentid/sponsorid'
    | '/voistlused/$tournamentid/tulemused'
    | '/admin/tournaments/$tournamentid/grupid/$groupid'
    | '/admin/tournaments/$tournamentid/ajakava/'
    | '/admin/tournaments/$tournamentid/grupid'
    | '/admin/tournaments/$tournamentid/mangud'
    | '/admin/tournaments/$tournamentid/pildid'
    | '/admin/tournaments/$tournamentid/tabelid'
    | '/voistlused/$tournamentid/tulemused/$groupid'
    | '/admin/tournaments/$tournamentid/ajakava/seaded'
    | '/admin/tournaments/$tournamentid/grupid/$groupid/'
    | '/admin/tournaments/$tournamentid/grupid/uus'
    | '/admin/tournaments/$tournamentid/grupid/$groupid/kohad'
    | '/admin/tournaments/$tournamentid/grupid/$groupid/mangud'
    | '/admin/tournaments/$tournamentid/grupid/$groupid/osalejad'
    | '/admin/tournaments/$tournamentid/grupid/$groupid/tabelid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/litsents/cancel'
    | '/litsents/success'
    | '/uudised/$blogid'
    | '/klubid'
    | '/kontakt'
    | '/litsents'
    | '/login'
    | '/profile'
    | '/reeglid'
    | '/register'
    | '/reiting'
    | '/tagasiside'
    | '/uudised'
    | '/voistlused'
    | '/admin/blog'
    | '/admin/clubs'
    | '/admin/dashboard'
    | '/admin/feedback'
    | '/admin/rating'
    | '/admin/tournaments'
    | '/admin/users'
    | '/profile/settings'
    | '/profile/tournaments'
    | '/voistlused/$tournamentid'
    | '/admin/tournaments/$tournamentid/kohad'
    | '/admin/blog/$blogid'
    | '/admin/blog/new'
    | '/admin/rating/$tournamentid'
    | '/admin/tournaments/$tournamentid'
    | '/admin/tournaments/new'
    | '/voistlused/$tournamentid/ajakava'
    | '/voistlused/$tournamentid/galerii'
    | '/voistlused/$tournamentid/juhend'
    | '/voistlused/$tournamentid/kohad'
    | '/voistlused/$tournamentid/lauad'
    | '/voistlused/$tournamentid/mangijad'
    | '/voistlused/$tournamentid/mangud'
    | '/voistlused/$tournamentid/meedia'
    | '/voistlused/$tournamentid/sponsorid'
    | '/voistlused/$tournamentid/tulemused'
    | '/admin/tournaments/$tournamentid/ajakava'
    | '/admin/tournaments/$tournamentid/grupid'
    | '/admin/tournaments/$tournamentid/mangud'
    | '/admin/tournaments/$tournamentid/pildid'
    | '/admin/tournaments/$tournamentid/tabelid'
    | '/voistlused/$tournamentid/tulemused/$groupid'
    | '/admin/tournaments/$tournamentid/ajakava/seaded'
    | '/admin/tournaments/$tournamentid/grupid/$groupid'
    | '/admin/tournaments/$tournamentid/grupid/uus'
    | '/admin/tournaments/$tournamentid/grupid/$groupid/kohad'
    | '/admin/tournaments/$tournamentid/grupid/$groupid/mangud'
    | '/admin/tournaments/$tournamentid/grupid/$groupid/osalejad'
    | '/admin/tournaments/$tournamentid/grupid/$groupid/tabelid'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/profile'
    | '/admin/blog'
    | '/admin/clubs'
    | '/admin/dashboard'
    | '/admin/tournaments'
    | '/voistlused/$tournamentid'
    | '/litsents/cancel'
    | '/litsents/success'
    | '/uudised/$blogid'
    | '/klubid/'
    | '/kontakt/'
    | '/litsents/'
    | '/login/'
    | '/profile/'
    | '/reeglid/'
    | '/register/'
    | '/reiting/'
    | '/tagasiside/'
    | '/uudised/'
    | '/voistlused/'
    | '/admin/tournaments/$tournamentid'
    | '/admin/blog/'
    | '/admin/clubs/'
    | '/admin/dashboard/'
    | '/admin/feedback/'
    | '/admin/rating/'
    | '/admin/tournaments/'
    | '/admin/users/'
    | '/profile/settings/'
    | '/profile/tournaments/'
    | '/voistlused/$tournamentid/'
    | '/admin/tournaments/$tournamentid/ajakava'
    | '/admin/tournaments/$tournamentid/kohad'
    | '/admin/blog/$blogid/'
    | '/admin/blog/new/'
    | '/admin/rating/$tournamentid/'
    | '/admin/tournaments/$tournamentid/'
    | '/admin/tournaments/new/'
    | '/voistlused/$tournamentid/ajakava/'
    | '/voistlused/$tournamentid/galerii/'
    | '/voistlused/$tournamentid/juhend/'
    | '/voistlused/$tournamentid/kohad/'
    | '/voistlused/$tournamentid/lauad/'
    | '/voistlused/$tournamentid/mangijad/'
    | '/voistlused/$tournamentid/mangud/'
    | '/voistlused/$tournamentid/meedia/'
    | '/voistlused/$tournamentid/sponsorid/'
    | '/voistlused/$tournamentid/tulemused/'
    | '/admin/tournaments/$tournamentid/grupid/$groupid'
    | '/admin/tournaments/$tournamentid/ajakava/'
    | '/admin/tournaments/$tournamentid/grupid/'
    | '/admin/tournaments/$tournamentid/mangud/'
    | '/admin/tournaments/$tournamentid/pildid/'
    | '/admin/tournaments/$tournamentid/tabelid/'
    | '/voistlused/$tournamentid/tulemused/$groupid/'
    | '/admin/tournaments/$tournamentid/ajakava/seaded/'
    | '/admin/tournaments/$tournamentid/grupid/$groupid/'
    | '/admin/tournaments/$tournamentid/grupid/uus/'
    | '/admin/tournaments/$tournamentid/grupid/$groupid/kohad/'
    | '/admin/tournaments/$tournamentid/grupid/$groupid/mangud/'
    | '/admin/tournaments/$tournamentid/grupid/$groupid/osalejad/'
    | '/admin/tournaments/$tournamentid/grupid/$groupid/tabelid/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
  ProfileLayoutRoute: typeof ProfileLayoutRouteWithChildren
  VoistlusedTournamentidLayoutRoute: typeof VoistlusedTournamentidLayoutRouteWithChildren
  LitsentsCancelRoute: typeof LitsentsCancelRoute
  LitsentsSuccessRoute: typeof LitsentsSuccessRoute
  UudisedBlogidRoute: typeof UudisedBlogidRoute
  KlubidIndexRoute: typeof KlubidIndexRoute
  KontaktIndexRoute: typeof KontaktIndexRoute
  LitsentsIndexRoute: typeof LitsentsIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  ReeglidIndexRoute: typeof ReeglidIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
  ReitingIndexRoute: typeof ReitingIndexRoute
  TagasisideIndexRoute: typeof TagasisideIndexRoute
  UudisedIndexRoute: typeof UudisedIndexRoute
  VoistlusedIndexRoute: typeof VoistlusedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voistlused/': {
      id: '/voistlused/'
      path: '/voistlused'
      fullPath: '/voistlused'
      preLoaderRoute: typeof VoistlusedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uudised/': {
      id: '/uudised/'
      path: '/uudised'
      fullPath: '/uudised'
      preLoaderRoute: typeof UudisedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tagasiside/': {
      id: '/tagasiside/'
      path: '/tagasiside'
      fullPath: '/tagasiside'
      preLoaderRoute: typeof TagasisideIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reiting/': {
      id: '/reiting/'
      path: '/reiting'
      fullPath: '/reiting'
      preLoaderRoute: typeof ReitingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reeglid/': {
      id: '/reeglid/'
      path: '/reeglid'
      fullPath: '/reeglid'
      preLoaderRoute: typeof ReeglidIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileLayoutRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/litsents/': {
      id: '/litsents/'
      path: '/litsents'
      fullPath: '/litsents'
      preLoaderRoute: typeof LitsentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt/': {
      id: '/kontakt/'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/klubid/': {
      id: '/klubid/'
      path: '/klubid'
      fullPath: '/klubid'
      preLoaderRoute: typeof KlubidIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uudised/$blogid': {
      id: '/uudised/$blogid'
      path: '/uudised/$blogid'
      fullPath: '/uudised/$blogid'
      preLoaderRoute: typeof UudisedBlogidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/litsents/success': {
      id: '/litsents/success'
      path: '/litsents/success'
      fullPath: '/litsents/success'
      preLoaderRoute: typeof LitsentsSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/litsents/cancel': {
      id: '/litsents/cancel'
      path: '/litsents/cancel'
      fullPath: '/litsents/cancel'
      preLoaderRoute: typeof LitsentsCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voistlused/$tournamentid': {
      id: '/voistlused/$tournamentid'
      path: '/voistlused/$tournamentid'
      fullPath: '/voistlused/$tournamentid'
      preLoaderRoute: typeof VoistlusedTournamentidLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tournaments': {
      id: '/admin/tournaments'
      path: '/tournaments'
      fullPath: '/admin/tournaments'
      preLoaderRoute: typeof AdminTournamentsLayoutRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardLayoutRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/clubs': {
      id: '/admin/clubs'
      path: '/clubs'
      fullPath: '/admin/clubs'
      preLoaderRoute: typeof AdminClubsLayoutRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogLayoutRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/voistlused/$tournamentid/': {
      id: '/voistlused/$tournamentid/'
      path: '/'
      fullPath: '/voistlused/$tournamentid/'
      preLoaderRoute: typeof VoistlusedTournamentidIndexRouteImport
      parentRoute: typeof VoistlusedTournamentidLayoutRoute
    }
    '/profile/tournaments/': {
      id: '/profile/tournaments/'
      path: '/tournaments'
      fullPath: '/profile/tournaments'
      preLoaderRoute: typeof ProfileTournamentsIndexRouteImport
      parentRoute: typeof ProfileLayoutRoute
    }
    '/profile/settings/': {
      id: '/profile/settings/'
      path: '/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof ProfileSettingsIndexRouteImport
      parentRoute: typeof ProfileLayoutRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/tournaments/': {
      id: '/admin/tournaments/'
      path: '/'
      fullPath: '/admin/tournaments/'
      preLoaderRoute: typeof AdminTournamentsIndexRouteImport
      parentRoute: typeof AdminTournamentsLayoutRoute
    }
    '/admin/rating/': {
      id: '/admin/rating/'
      path: '/rating'
      fullPath: '/admin/rating'
      preLoaderRoute: typeof AdminRatingIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/feedback/': {
      id: '/admin/feedback/'
      path: '/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminFeedbackIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/dashboard/': {
      id: '/admin/dashboard/'
      path: '/'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof AdminDashboardLayoutRoute
    }
    '/admin/clubs/': {
      id: '/admin/clubs/'
      path: '/'
      fullPath: '/admin/clubs/'
      preLoaderRoute: typeof AdminClubsIndexRouteImport
      parentRoute: typeof AdminClubsLayoutRoute
    }
    '/admin/blog/': {
      id: '/admin/blog/'
      path: '/'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AdminBlogIndexRouteImport
      parentRoute: typeof AdminBlogLayoutRoute
    }
    '/admin/tournaments/$tournamentid': {
      id: '/admin/tournaments/$tournamentid'
      path: '/$tournamentid'
      fullPath: '/admin/tournaments/$tournamentid'
      preLoaderRoute: typeof AdminTournamentsTournamentidLayoutRouteImport
      parentRoute: typeof AdminTournamentsLayoutRoute
    }
    '/voistlused/$tournamentid/tulemused/': {
      id: '/voistlused/$tournamentid/tulemused/'
      path: '/tulemused'
      fullPath: '/voistlused/$tournamentid/tulemused'
      preLoaderRoute: typeof VoistlusedTournamentidTulemusedIndexRouteImport
      parentRoute: typeof VoistlusedTournamentidLayoutRoute
    }
    '/voistlused/$tournamentid/sponsorid/': {
      id: '/voistlused/$tournamentid/sponsorid/'
      path: '/sponsorid'
      fullPath: '/voistlused/$tournamentid/sponsorid'
      preLoaderRoute: typeof VoistlusedTournamentidSponsoridIndexRouteImport
      parentRoute: typeof VoistlusedTournamentidLayoutRoute
    }
    '/voistlused/$tournamentid/meedia/': {
      id: '/voistlused/$tournamentid/meedia/'
      path: '/meedia'
      fullPath: '/voistlused/$tournamentid/meedia'
      preLoaderRoute: typeof VoistlusedTournamentidMeediaIndexRouteImport
      parentRoute: typeof VoistlusedTournamentidLayoutRoute
    }
    '/voistlused/$tournamentid/mangud/': {
      id: '/voistlused/$tournamentid/mangud/'
      path: '/mangud'
      fullPath: '/voistlused/$tournamentid/mangud'
      preLoaderRoute: typeof VoistlusedTournamentidMangudIndexRouteImport
      parentRoute: typeof VoistlusedTournamentidLayoutRoute
    }
    '/voistlused/$tournamentid/mangijad/': {
      id: '/voistlused/$tournamentid/mangijad/'
      path: '/mangijad'
      fullPath: '/voistlused/$tournamentid/mangijad'
      preLoaderRoute: typeof VoistlusedTournamentidMangijadIndexRouteImport
      parentRoute: typeof VoistlusedTournamentidLayoutRoute
    }
    '/voistlused/$tournamentid/lauad/': {
      id: '/voistlused/$tournamentid/lauad/'
      path: '/lauad'
      fullPath: '/voistlused/$tournamentid/lauad'
      preLoaderRoute: typeof VoistlusedTournamentidLauadIndexRouteImport
      parentRoute: typeof VoistlusedTournamentidLayoutRoute
    }
    '/voistlused/$tournamentid/kohad/': {
      id: '/voistlused/$tournamentid/kohad/'
      path: '/kohad'
      fullPath: '/voistlused/$tournamentid/kohad'
      preLoaderRoute: typeof VoistlusedTournamentidKohadIndexRouteImport
      parentRoute: typeof VoistlusedTournamentidLayoutRoute
    }
    '/voistlused/$tournamentid/juhend/': {
      id: '/voistlused/$tournamentid/juhend/'
      path: '/juhend'
      fullPath: '/voistlused/$tournamentid/juhend'
      preLoaderRoute: typeof VoistlusedTournamentidJuhendIndexRouteImport
      parentRoute: typeof VoistlusedTournamentidLayoutRoute
    }
    '/voistlused/$tournamentid/galerii/': {
      id: '/voistlused/$tournamentid/galerii/'
      path: '/galerii'
      fullPath: '/voistlused/$tournamentid/galerii'
      preLoaderRoute: typeof VoistlusedTournamentidGaleriiIndexRouteImport
      parentRoute: typeof VoistlusedTournamentidLayoutRoute
    }
    '/voistlused/$tournamentid/ajakava/': {
      id: '/voistlused/$tournamentid/ajakava/'
      path: '/ajakava'
      fullPath: '/voistlused/$tournamentid/ajakava'
      preLoaderRoute: typeof VoistlusedTournamentidAjakavaIndexRouteImport
      parentRoute: typeof VoistlusedTournamentidLayoutRoute
    }
    '/admin/tournaments/new/': {
      id: '/admin/tournaments/new/'
      path: '/new'
      fullPath: '/admin/tournaments/new'
      preLoaderRoute: typeof AdminTournamentsNewIndexRouteImport
      parentRoute: typeof AdminTournamentsLayoutRoute
    }
    '/admin/tournaments/$tournamentid/': {
      id: '/admin/tournaments/$tournamentid/'
      path: '/'
      fullPath: '/admin/tournaments/$tournamentid/'
      preLoaderRoute: typeof AdminTournamentsTournamentidIndexRouteImport
      parentRoute: typeof AdminTournamentsTournamentidLayoutRoute
    }
    '/admin/rating/$tournamentid/': {
      id: '/admin/rating/$tournamentid/'
      path: '/rating/$tournamentid'
      fullPath: '/admin/rating/$tournamentid'
      preLoaderRoute: typeof AdminRatingTournamentidIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/blog/new/': {
      id: '/admin/blog/new/'
      path: '/new'
      fullPath: '/admin/blog/new'
      preLoaderRoute: typeof AdminBlogNewIndexRouteImport
      parentRoute: typeof AdminBlogLayoutRoute
    }
    '/admin/blog/$blogid/': {
      id: '/admin/blog/$blogid/'
      path: '/$blogid'
      fullPath: '/admin/blog/$blogid'
      preLoaderRoute: typeof AdminBlogBlogidIndexRouteImport
      parentRoute: typeof AdminBlogLayoutRoute
    }
    '/admin/tournaments/$tournamentid/kohad': {
      id: '/admin/tournaments/$tournamentid/kohad'
      path: '/kohad'
      fullPath: '/admin/tournaments/$tournamentid/kohad'
      preLoaderRoute: typeof AdminTournamentsTournamentidKohadRouteImport
      parentRoute: typeof AdminTournamentsTournamentidLayoutRoute
    }
    '/admin/tournaments/$tournamentid/ajakava': {
      id: '/admin/tournaments/$tournamentid/ajakava'
      path: '/ajakava'
      fullPath: '/admin/tournaments/$tournamentid/ajakava'
      preLoaderRoute: typeof AdminTournamentsTournamentidAjakavaLayoutRouteImport
      parentRoute: typeof AdminTournamentsTournamentidLayoutRoute
    }
    '/voistlused/$tournamentid/tulemused/$groupid/': {
      id: '/voistlused/$tournamentid/tulemused/$groupid/'
      path: '/tulemused/$groupid'
      fullPath: '/voistlused/$tournamentid/tulemused/$groupid'
      preLoaderRoute: typeof VoistlusedTournamentidTulemusedGroupidIndexRouteImport
      parentRoute: typeof VoistlusedTournamentidLayoutRoute
    }
    '/admin/tournaments/$tournamentid/tabelid/': {
      id: '/admin/tournaments/$tournamentid/tabelid/'
      path: '/tabelid'
      fullPath: '/admin/tournaments/$tournamentid/tabelid'
      preLoaderRoute: typeof AdminTournamentsTournamentidTabelidIndexRouteImport
      parentRoute: typeof AdminTournamentsTournamentidLayoutRoute
    }
    '/admin/tournaments/$tournamentid/pildid/': {
      id: '/admin/tournaments/$tournamentid/pildid/'
      path: '/pildid'
      fullPath: '/admin/tournaments/$tournamentid/pildid'
      preLoaderRoute: typeof AdminTournamentsTournamentidPildidIndexRouteImport
      parentRoute: typeof AdminTournamentsTournamentidLayoutRoute
    }
    '/admin/tournaments/$tournamentid/mangud/': {
      id: '/admin/tournaments/$tournamentid/mangud/'
      path: '/mangud'
      fullPath: '/admin/tournaments/$tournamentid/mangud'
      preLoaderRoute: typeof AdminTournamentsTournamentidMangudIndexRouteImport
      parentRoute: typeof AdminTournamentsTournamentidLayoutRoute
    }
    '/admin/tournaments/$tournamentid/grupid/': {
      id: '/admin/tournaments/$tournamentid/grupid/'
      path: '/grupid'
      fullPath: '/admin/tournaments/$tournamentid/grupid'
      preLoaderRoute: typeof AdminTournamentsTournamentidGrupidIndexRouteImport
      parentRoute: typeof AdminTournamentsTournamentidLayoutRoute
    }
    '/admin/tournaments/$tournamentid/ajakava/': {
      id: '/admin/tournaments/$tournamentid/ajakava/'
      path: '/'
      fullPath: '/admin/tournaments/$tournamentid/ajakava/'
      preLoaderRoute: typeof AdminTournamentsTournamentidAjakavaIndexRouteImport
      parentRoute: typeof AdminTournamentsTournamentidAjakavaLayoutRoute
    }
    '/admin/tournaments/$tournamentid/grupid/$groupid': {
      id: '/admin/tournaments/$tournamentid/grupid/$groupid'
      path: '/grupid/$groupid'
      fullPath: '/admin/tournaments/$tournamentid/grupid/$groupid'
      preLoaderRoute: typeof AdminTournamentsTournamentidGrupidGroupidLayoutRouteImport
      parentRoute: typeof AdminTournamentsTournamentidLayoutRoute
    }
    '/admin/tournaments/$tournamentid/grupid/uus/': {
      id: '/admin/tournaments/$tournamentid/grupid/uus/'
      path: '/grupid/uus'
      fullPath: '/admin/tournaments/$tournamentid/grupid/uus'
      preLoaderRoute: typeof AdminTournamentsTournamentidGrupidUusIndexRouteImport
      parentRoute: typeof AdminTournamentsTournamentidLayoutRoute
    }
    '/admin/tournaments/$tournamentid/grupid/$groupid/': {
      id: '/admin/tournaments/$tournamentid/grupid/$groupid/'
      path: '/'
      fullPath: '/admin/tournaments/$tournamentid/grupid/$groupid/'
      preLoaderRoute: typeof AdminTournamentsTournamentidGrupidGroupidIndexRouteImport
      parentRoute: typeof AdminTournamentsTournamentidGrupidGroupidLayoutRoute
    }
    '/admin/tournaments/$tournamentid/ajakava/seaded/': {
      id: '/admin/tournaments/$tournamentid/ajakava/seaded/'
      path: '/seaded'
      fullPath: '/admin/tournaments/$tournamentid/ajakava/seaded'
      preLoaderRoute: typeof AdminTournamentsTournamentidAjakavaSeadedIndexRouteImport
      parentRoute: typeof AdminTournamentsTournamentidAjakavaLayoutRoute
    }
    '/admin/tournaments/$tournamentid/grupid/$groupid/tabelid/': {
      id: '/admin/tournaments/$tournamentid/grupid/$groupid/tabelid/'
      path: '/tabelid'
      fullPath: '/admin/tournaments/$tournamentid/grupid/$groupid/tabelid'
      preLoaderRoute: typeof AdminTournamentsTournamentidGrupidGroupidTabelidIndexRouteImport
      parentRoute: typeof AdminTournamentsTournamentidGrupidGroupidLayoutRoute
    }
    '/admin/tournaments/$tournamentid/grupid/$groupid/osalejad/': {
      id: '/admin/tournaments/$tournamentid/grupid/$groupid/osalejad/'
      path: '/osalejad'
      fullPath: '/admin/tournaments/$tournamentid/grupid/$groupid/osalejad'
      preLoaderRoute: typeof AdminTournamentsTournamentidGrupidGroupidOsalejadIndexRouteImport
      parentRoute: typeof AdminTournamentsTournamentidGrupidGroupidLayoutRoute
    }
    '/admin/tournaments/$tournamentid/grupid/$groupid/mangud/': {
      id: '/admin/tournaments/$tournamentid/grupid/$groupid/mangud/'
      path: '/mangud'
      fullPath: '/admin/tournaments/$tournamentid/grupid/$groupid/mangud'
      preLoaderRoute: typeof AdminTournamentsTournamentidGrupidGroupidMangudIndexRouteImport
      parentRoute: typeof AdminTournamentsTournamentidGrupidGroupidLayoutRoute
    }
    '/admin/tournaments/$tournamentid/grupid/$groupid/kohad/': {
      id: '/admin/tournaments/$tournamentid/grupid/$groupid/kohad/'
      path: '/kohad'
      fullPath: '/admin/tournaments/$tournamentid/grupid/$groupid/kohad'
      preLoaderRoute: typeof AdminTournamentsTournamentidGrupidGroupidKohadIndexRouteImport
      parentRoute: typeof AdminTournamentsTournamentidGrupidGroupidLayoutRoute
    }
  }
}

interface AdminBlogLayoutRouteChildren {
  AdminBlogIndexRoute: typeof AdminBlogIndexRoute
  AdminBlogBlogidIndexRoute: typeof AdminBlogBlogidIndexRoute
  AdminBlogNewIndexRoute: typeof AdminBlogNewIndexRoute
}

const AdminBlogLayoutRouteChildren: AdminBlogLayoutRouteChildren = {
  AdminBlogIndexRoute: AdminBlogIndexRoute,
  AdminBlogBlogidIndexRoute: AdminBlogBlogidIndexRoute,
  AdminBlogNewIndexRoute: AdminBlogNewIndexRoute,
}

const AdminBlogLayoutRouteWithChildren = AdminBlogLayoutRoute._addFileChildren(
  AdminBlogLayoutRouteChildren,
)

interface AdminClubsLayoutRouteChildren {
  AdminClubsIndexRoute: typeof AdminClubsIndexRoute
}

const AdminClubsLayoutRouteChildren: AdminClubsLayoutRouteChildren = {
  AdminClubsIndexRoute: AdminClubsIndexRoute,
}

const AdminClubsLayoutRouteWithChildren =
  AdminClubsLayoutRoute._addFileChildren(AdminClubsLayoutRouteChildren)

interface AdminDashboardLayoutRouteChildren {
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
}

const AdminDashboardLayoutRouteChildren: AdminDashboardLayoutRouteChildren = {
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
}

const AdminDashboardLayoutRouteWithChildren =
  AdminDashboardLayoutRoute._addFileChildren(AdminDashboardLayoutRouteChildren)

interface AdminTournamentsTournamentidAjakavaLayoutRouteChildren {
  AdminTournamentsTournamentidAjakavaIndexRoute: typeof AdminTournamentsTournamentidAjakavaIndexRoute
  AdminTournamentsTournamentidAjakavaSeadedIndexRoute: typeof AdminTournamentsTournamentidAjakavaSeadedIndexRoute
}

const AdminTournamentsTournamentidAjakavaLayoutRouteChildren: AdminTournamentsTournamentidAjakavaLayoutRouteChildren =
  {
    AdminTournamentsTournamentidAjakavaIndexRoute:
      AdminTournamentsTournamentidAjakavaIndexRoute,
    AdminTournamentsTournamentidAjakavaSeadedIndexRoute:
      AdminTournamentsTournamentidAjakavaSeadedIndexRoute,
  }

const AdminTournamentsTournamentidAjakavaLayoutRouteWithChildren =
  AdminTournamentsTournamentidAjakavaLayoutRoute._addFileChildren(
    AdminTournamentsTournamentidAjakavaLayoutRouteChildren,
  )

interface AdminTournamentsTournamentidGrupidGroupidLayoutRouteChildren {
  AdminTournamentsTournamentidGrupidGroupidIndexRoute: typeof AdminTournamentsTournamentidGrupidGroupidIndexRoute
  AdminTournamentsTournamentidGrupidGroupidKohadIndexRoute: typeof AdminTournamentsTournamentidGrupidGroupidKohadIndexRoute
  AdminTournamentsTournamentidGrupidGroupidMangudIndexRoute: typeof AdminTournamentsTournamentidGrupidGroupidMangudIndexRoute
  AdminTournamentsTournamentidGrupidGroupidOsalejadIndexRoute: typeof AdminTournamentsTournamentidGrupidGroupidOsalejadIndexRoute
  AdminTournamentsTournamentidGrupidGroupidTabelidIndexRoute: typeof AdminTournamentsTournamentidGrupidGroupidTabelidIndexRoute
}

const AdminTournamentsTournamentidGrupidGroupidLayoutRouteChildren: AdminTournamentsTournamentidGrupidGroupidLayoutRouteChildren =
  {
    AdminTournamentsTournamentidGrupidGroupidIndexRoute:
      AdminTournamentsTournamentidGrupidGroupidIndexRoute,
    AdminTournamentsTournamentidGrupidGroupidKohadIndexRoute:
      AdminTournamentsTournamentidGrupidGroupidKohadIndexRoute,
    AdminTournamentsTournamentidGrupidGroupidMangudIndexRoute:
      AdminTournamentsTournamentidGrupidGroupidMangudIndexRoute,
    AdminTournamentsTournamentidGrupidGroupidOsalejadIndexRoute:
      AdminTournamentsTournamentidGrupidGroupidOsalejadIndexRoute,
    AdminTournamentsTournamentidGrupidGroupidTabelidIndexRoute:
      AdminTournamentsTournamentidGrupidGroupidTabelidIndexRoute,
  }

const AdminTournamentsTournamentidGrupidGroupidLayoutRouteWithChildren =
  AdminTournamentsTournamentidGrupidGroupidLayoutRoute._addFileChildren(
    AdminTournamentsTournamentidGrupidGroupidLayoutRouteChildren,
  )

interface AdminTournamentsTournamentidLayoutRouteChildren {
  AdminTournamentsTournamentidAjakavaLayoutRoute: typeof AdminTournamentsTournamentidAjakavaLayoutRouteWithChildren
  AdminTournamentsTournamentidKohadRoute: typeof AdminTournamentsTournamentidKohadRoute
  AdminTournamentsTournamentidIndexRoute: typeof AdminTournamentsTournamentidIndexRoute
  AdminTournamentsTournamentidGrupidGroupidLayoutRoute: typeof AdminTournamentsTournamentidGrupidGroupidLayoutRouteWithChildren
  AdminTournamentsTournamentidGrupidIndexRoute: typeof AdminTournamentsTournamentidGrupidIndexRoute
  AdminTournamentsTournamentidMangudIndexRoute: typeof AdminTournamentsTournamentidMangudIndexRoute
  AdminTournamentsTournamentidPildidIndexRoute: typeof AdminTournamentsTournamentidPildidIndexRoute
  AdminTournamentsTournamentidTabelidIndexRoute: typeof AdminTournamentsTournamentidTabelidIndexRoute
  AdminTournamentsTournamentidGrupidUusIndexRoute: typeof AdminTournamentsTournamentidGrupidUusIndexRoute
}

const AdminTournamentsTournamentidLayoutRouteChildren: AdminTournamentsTournamentidLayoutRouteChildren =
  {
    AdminTournamentsTournamentidAjakavaLayoutRoute:
      AdminTournamentsTournamentidAjakavaLayoutRouteWithChildren,
    AdminTournamentsTournamentidKohadRoute:
      AdminTournamentsTournamentidKohadRoute,
    AdminTournamentsTournamentidIndexRoute:
      AdminTournamentsTournamentidIndexRoute,
    AdminTournamentsTournamentidGrupidGroupidLayoutRoute:
      AdminTournamentsTournamentidGrupidGroupidLayoutRouteWithChildren,
    AdminTournamentsTournamentidGrupidIndexRoute:
      AdminTournamentsTournamentidGrupidIndexRoute,
    AdminTournamentsTournamentidMangudIndexRoute:
      AdminTournamentsTournamentidMangudIndexRoute,
    AdminTournamentsTournamentidPildidIndexRoute:
      AdminTournamentsTournamentidPildidIndexRoute,
    AdminTournamentsTournamentidTabelidIndexRoute:
      AdminTournamentsTournamentidTabelidIndexRoute,
    AdminTournamentsTournamentidGrupidUusIndexRoute:
      AdminTournamentsTournamentidGrupidUusIndexRoute,
  }

const AdminTournamentsTournamentidLayoutRouteWithChildren =
  AdminTournamentsTournamentidLayoutRoute._addFileChildren(
    AdminTournamentsTournamentidLayoutRouteChildren,
  )

interface AdminTournamentsLayoutRouteChildren {
  AdminTournamentsTournamentidLayoutRoute: typeof AdminTournamentsTournamentidLayoutRouteWithChildren
  AdminTournamentsIndexRoute: typeof AdminTournamentsIndexRoute
  AdminTournamentsNewIndexRoute: typeof AdminTournamentsNewIndexRoute
}

const AdminTournamentsLayoutRouteChildren: AdminTournamentsLayoutRouteChildren =
  {
    AdminTournamentsTournamentidLayoutRoute:
      AdminTournamentsTournamentidLayoutRouteWithChildren,
    AdminTournamentsIndexRoute: AdminTournamentsIndexRoute,
    AdminTournamentsNewIndexRoute: AdminTournamentsNewIndexRoute,
  }

const AdminTournamentsLayoutRouteWithChildren =
  AdminTournamentsLayoutRoute._addFileChildren(
    AdminTournamentsLayoutRouteChildren,
  )

interface AdminLayoutRouteChildren {
  AdminBlogLayoutRoute: typeof AdminBlogLayoutRouteWithChildren
  AdminClubsLayoutRoute: typeof AdminClubsLayoutRouteWithChildren
  AdminDashboardLayoutRoute: typeof AdminDashboardLayoutRouteWithChildren
  AdminTournamentsLayoutRoute: typeof AdminTournamentsLayoutRouteWithChildren
  AdminFeedbackIndexRoute: typeof AdminFeedbackIndexRoute
  AdminRatingIndexRoute: typeof AdminRatingIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminRatingTournamentidIndexRoute: typeof AdminRatingTournamentidIndexRoute
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminBlogLayoutRoute: AdminBlogLayoutRouteWithChildren,
  AdminClubsLayoutRoute: AdminClubsLayoutRouteWithChildren,
  AdminDashboardLayoutRoute: AdminDashboardLayoutRouteWithChildren,
  AdminTournamentsLayoutRoute: AdminTournamentsLayoutRouteWithChildren,
  AdminFeedbackIndexRoute: AdminFeedbackIndexRoute,
  AdminRatingIndexRoute: AdminRatingIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminRatingTournamentidIndexRoute: AdminRatingTournamentidIndexRoute,
}

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(
  AdminLayoutRouteChildren,
)

interface ProfileLayoutRouteChildren {
  ProfileIndexRoute: typeof ProfileIndexRoute
  ProfileSettingsIndexRoute: typeof ProfileSettingsIndexRoute
  ProfileTournamentsIndexRoute: typeof ProfileTournamentsIndexRoute
}

const ProfileLayoutRouteChildren: ProfileLayoutRouteChildren = {
  ProfileIndexRoute: ProfileIndexRoute,
  ProfileSettingsIndexRoute: ProfileSettingsIndexRoute,
  ProfileTournamentsIndexRoute: ProfileTournamentsIndexRoute,
}

const ProfileLayoutRouteWithChildren = ProfileLayoutRoute._addFileChildren(
  ProfileLayoutRouteChildren,
)

interface VoistlusedTournamentidLayoutRouteChildren {
  VoistlusedTournamentidIndexRoute: typeof VoistlusedTournamentidIndexRoute
  VoistlusedTournamentidAjakavaIndexRoute: typeof VoistlusedTournamentidAjakavaIndexRoute
  VoistlusedTournamentidGaleriiIndexRoute: typeof VoistlusedTournamentidGaleriiIndexRoute
  VoistlusedTournamentidJuhendIndexRoute: typeof VoistlusedTournamentidJuhendIndexRoute
  VoistlusedTournamentidKohadIndexRoute: typeof VoistlusedTournamentidKohadIndexRoute
  VoistlusedTournamentidLauadIndexRoute: typeof VoistlusedTournamentidLauadIndexRoute
  VoistlusedTournamentidMangijadIndexRoute: typeof VoistlusedTournamentidMangijadIndexRoute
  VoistlusedTournamentidMangudIndexRoute: typeof VoistlusedTournamentidMangudIndexRoute
  VoistlusedTournamentidMeediaIndexRoute: typeof VoistlusedTournamentidMeediaIndexRoute
  VoistlusedTournamentidSponsoridIndexRoute: typeof VoistlusedTournamentidSponsoridIndexRoute
  VoistlusedTournamentidTulemusedIndexRoute: typeof VoistlusedTournamentidTulemusedIndexRoute
  VoistlusedTournamentidTulemusedGroupidIndexRoute: typeof VoistlusedTournamentidTulemusedGroupidIndexRoute
}

const VoistlusedTournamentidLayoutRouteChildren: VoistlusedTournamentidLayoutRouteChildren =
  {
    VoistlusedTournamentidIndexRoute: VoistlusedTournamentidIndexRoute,
    VoistlusedTournamentidAjakavaIndexRoute:
      VoistlusedTournamentidAjakavaIndexRoute,
    VoistlusedTournamentidGaleriiIndexRoute:
      VoistlusedTournamentidGaleriiIndexRoute,
    VoistlusedTournamentidJuhendIndexRoute:
      VoistlusedTournamentidJuhendIndexRoute,
    VoistlusedTournamentidKohadIndexRoute:
      VoistlusedTournamentidKohadIndexRoute,
    VoistlusedTournamentidLauadIndexRoute:
      VoistlusedTournamentidLauadIndexRoute,
    VoistlusedTournamentidMangijadIndexRoute:
      VoistlusedTournamentidMangijadIndexRoute,
    VoistlusedTournamentidMangudIndexRoute:
      VoistlusedTournamentidMangudIndexRoute,
    VoistlusedTournamentidMeediaIndexRoute:
      VoistlusedTournamentidMeediaIndexRoute,
    VoistlusedTournamentidSponsoridIndexRoute:
      VoistlusedTournamentidSponsoridIndexRoute,
    VoistlusedTournamentidTulemusedIndexRoute:
      VoistlusedTournamentidTulemusedIndexRoute,
    VoistlusedTournamentidTulemusedGroupidIndexRoute:
      VoistlusedTournamentidTulemusedGroupidIndexRoute,
  }

const VoistlusedTournamentidLayoutRouteWithChildren =
  VoistlusedTournamentidLayoutRoute._addFileChildren(
    VoistlusedTournamentidLayoutRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
  ProfileLayoutRoute: ProfileLayoutRouteWithChildren,
  VoistlusedTournamentidLayoutRoute:
    VoistlusedTournamentidLayoutRouteWithChildren,
  LitsentsCancelRoute: LitsentsCancelRoute,
  LitsentsSuccessRoute: LitsentsSuccessRoute,
  UudisedBlogidRoute: UudisedBlogidRoute,
  KlubidIndexRoute: KlubidIndexRoute,
  KontaktIndexRoute: KontaktIndexRoute,
  LitsentsIndexRoute: LitsentsIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  ReeglidIndexRoute: ReeglidIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
  ReitingIndexRoute: ReitingIndexRoute,
  TagasisideIndexRoute: TagasisideIndexRoute,
  UudisedIndexRoute: UudisedIndexRoute,
  VoistlusedIndexRoute: VoistlusedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
