/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProfileLayoutImport } from './routes/profile/layout'
import { Route as AdminLayoutImport } from './routes/admin/layout'
import { Route as IndexImport } from './routes/index'
import { Route as VoistlusedIndexImport } from './routes/voistlused/index'
import { Route as UudisedIndexImport } from './routes/uudised/index'
import { Route as TagasisideIndexImport } from './routes/tagasiside/index'
import { Route as ReitingIndexImport } from './routes/reiting/index'
import { Route as RegisterIndexImport } from './routes/register/index'
import { Route as ReeglidIndexImport } from './routes/reeglid/index'
import { Route as ProfileIndexImport } from './routes/profile/index'
import { Route as LoginIndexImport } from './routes/login/index'
import { Route as KontaktIndexImport } from './routes/kontakt/index'
import { Route as KlubidIndexImport } from './routes/klubid/index'
import { Route as UudisedBlogidImport } from './routes/uudised/$blogid'
import { Route as VoistlusedTournamentidLayoutImport } from './routes/voistlused/$tournamentid/layout'
import { Route as AdminTournamentsLayoutImport } from './routes/admin/tournaments/layout'
import { Route as AdminDashboardLayoutImport } from './routes/admin/dashboard/layout'
import { Route as AdminClubsLayoutImport } from './routes/admin/clubs/layout'
import { Route as AdminBlogLayoutImport } from './routes/admin/blog/layout'
import { Route as VoistlusedTournamentidIndexImport } from './routes/voistlused/$tournamentid/index'
import { Route as ProfileTournamentsIndexImport } from './routes/profile/tournaments/index'
import { Route as ProfileSettingsIndexImport } from './routes/profile/settings/index'
import { Route as EpoodLitsentsIndexImport } from './routes/epood/litsents/index'
import { Route as AdminUsersIndexImport } from './routes/admin/users/index'
import { Route as AdminTournamentsIndexImport } from './routes/admin/tournaments/index'
import { Route as AdminRatingIndexImport } from './routes/admin/rating/index'
import { Route as AdminFeedbackIndexImport } from './routes/admin/feedback/index'
import { Route as AdminDashboardIndexImport } from './routes/admin/dashboard/index'
import { Route as AdminClubsIndexImport } from './routes/admin/clubs/index'
import { Route as AdminBlogIndexImport } from './routes/admin/blog/index'
import { Route as EpoodLitsentsSuccessImport } from './routes/epood/litsents/success'
import { Route as EpoodLitsentsCancelImport } from './routes/epood/litsents/cancel'
import { Route as AdminTournamentsTournamentidLayoutImport } from './routes/admin/tournaments/$tournamentid/layout'
import { Route as VoistlusedTournamentidTulemusedIndexImport } from './routes/voistlused/$tournamentid/tulemused/index'
import { Route as VoistlusedTournamentidSponsoridIndexImport } from './routes/voistlused/$tournamentid/sponsorid/index'
import { Route as VoistlusedTournamentidMeediaIndexImport } from './routes/voistlused/$tournamentid/meedia/index'
import { Route as VoistlusedTournamentidMangudIndexImport } from './routes/voistlused/$tournamentid/mangud/index'
import { Route as VoistlusedTournamentidMangijadIndexImport } from './routes/voistlused/$tournamentid/mangijad/index'
import { Route as VoistlusedTournamentidLauadIndexImport } from './routes/voistlused/$tournamentid/lauad/index'
import { Route as VoistlusedTournamentidKohadIndexImport } from './routes/voistlused/$tournamentid/kohad/index'
import { Route as VoistlusedTournamentidJuhendIndexImport } from './routes/voistlused/$tournamentid/juhend/index'
import { Route as VoistlusedTournamentidGaleriiIndexImport } from './routes/voistlused/$tournamentid/galerii/index'
import { Route as VoistlusedTournamentidAjakavaIndexImport } from './routes/voistlused/$tournamentid/ajakava/index'
import { Route as AdminTournamentsNewIndexImport } from './routes/admin/tournaments/new/index'
import { Route as AdminTournamentsTournamentidIndexImport } from './routes/admin/tournaments/$tournamentid/index'
import { Route as AdminRatingTournamentidIndexImport } from './routes/admin/rating/$tournamentid/index'
import { Route as AdminBlogNewIndexImport } from './routes/admin/blog/new/index'
import { Route as AdminBlogBlogidIndexImport } from './routes/admin/blog/$blogid/index'
import { Route as AdminTournamentsTournamentidAjakavaLayoutImport } from './routes/admin/tournaments/$tournamentid/ajakava/layout'
import { Route as VoistlusedTournamentidTulemusedGroupidIndexImport } from './routes/voistlused/$tournamentid/tulemused/$groupid/index'
import { Route as AdminTournamentsTournamentidPildidIndexImport } from './routes/admin/tournaments/$tournamentid/pildid/index'
import { Route as AdminTournamentsTournamentidMangudIndexImport } from './routes/admin/tournaments/$tournamentid/mangud/index'
import { Route as AdminTournamentsTournamentidGrupidIndexImport } from './routes/admin/tournaments/$tournamentid/grupid/index'
import { Route as AdminTournamentsTournamentidAjakavaIndexImport } from './routes/admin/tournaments/$tournamentid/ajakava/index'
import { Route as AdminTournamentsTournamentidGrupidGroupidLayoutImport } from './routes/admin/tournaments/$tournamentid/grupid/$groupid/layout'
import { Route as AdminTournamentsTournamentidGrupidUusIndexImport } from './routes/admin/tournaments/$tournamentid/grupid/uus/index'
import { Route as AdminTournamentsTournamentidGrupidGroupidIndexImport } from './routes/admin/tournaments/$tournamentid/grupid/$groupid/index'
import { Route as AdminTournamentsTournamentidAjakavaSeadedIndexImport } from './routes/admin/tournaments/$tournamentid/ajakava/seaded/index'
import { Route as AdminTournamentsTournamentidGrupidGroupidTabelidIndexImport } from './routes/admin/tournaments/$tournamentid/grupid/$groupid/tabelid/index'
import { Route as AdminTournamentsTournamentidGrupidGroupidOsalejadIndexImport } from './routes/admin/tournaments/$tournamentid/grupid/$groupid/osalejad/index'
import { Route as AdminTournamentsTournamentidGrupidGroupidMangudIndexImport } from './routes/admin/tournaments/$tournamentid/grupid/$groupid/mangud/index'
import { Route as AdminTournamentsTournamentidGrupidGroupidKohadIndexImport } from './routes/admin/tournaments/$tournamentid/grupid/$groupid/kohad/index'

// Create/Update Routes

const ProfileLayoutRoute = ProfileLayoutImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const AdminLayoutRoute = AdminLayoutImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const VoistlusedIndexRoute = VoistlusedIndexImport.update({
  id: '/voistlused/',
  path: '/voistlused/',
  getParentRoute: () => rootRoute,
} as any)

const UudisedIndexRoute = UudisedIndexImport.update({
  id: '/uudised/',
  path: '/uudised/',
  getParentRoute: () => rootRoute,
} as any)

const TagasisideIndexRoute = TagasisideIndexImport.update({
  id: '/tagasiside/',
  path: '/tagasiside/',
  getParentRoute: () => rootRoute,
} as any)

const ReitingIndexRoute = ReitingIndexImport.update({
  id: '/reiting/',
  path: '/reiting/',
  getParentRoute: () => rootRoute,
} as any)

const RegisterIndexRoute = RegisterIndexImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRoute,
} as any)

const ReeglidIndexRoute = ReeglidIndexImport.update({
  id: '/reeglid/',
  path: '/reeglid/',
  getParentRoute: () => rootRoute,
} as any)

const ProfileIndexRoute = ProfileIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileLayoutRoute,
} as any)

const LoginIndexRoute = LoginIndexImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const KontaktIndexRoute = KontaktIndexImport.update({
  id: '/kontakt/',
  path: '/kontakt/',
  getParentRoute: () => rootRoute,
} as any)

const KlubidIndexRoute = KlubidIndexImport.update({
  id: '/klubid/',
  path: '/klubid/',
  getParentRoute: () => rootRoute,
} as any)

const UudisedBlogidRoute = UudisedBlogidImport.update({
  id: '/uudised/$blogid',
  path: '/uudised/$blogid',
  getParentRoute: () => rootRoute,
} as any)

const VoistlusedTournamentidLayoutRoute =
  VoistlusedTournamentidLayoutImport.update({
    id: '/voistlused/$tournamentid',
    path: '/voistlused/$tournamentid',
    getParentRoute: () => rootRoute,
  } as any)

const AdminTournamentsLayoutRoute = AdminTournamentsLayoutImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => AdminLayoutRoute,
} as any)

const AdminDashboardLayoutRoute = AdminDashboardLayoutImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminLayoutRoute,
} as any)

const AdminClubsLayoutRoute = AdminClubsLayoutImport.update({
  id: '/clubs',
  path: '/clubs',
  getParentRoute: () => AdminLayoutRoute,
} as any)

const AdminBlogLayoutRoute = AdminBlogLayoutImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminLayoutRoute,
} as any)

const VoistlusedTournamentidIndexRoute =
  VoistlusedTournamentidIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => VoistlusedTournamentidLayoutRoute,
  } as any)

const ProfileTournamentsIndexRoute = ProfileTournamentsIndexImport.update({
  id: '/tournaments/',
  path: '/tournaments/',
  getParentRoute: () => ProfileLayoutRoute,
} as any)

const ProfileSettingsIndexRoute = ProfileSettingsIndexImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => ProfileLayoutRoute,
} as any)

const EpoodLitsentsIndexRoute = EpoodLitsentsIndexImport.update({
  id: '/epood/litsents/',
  path: '/epood/litsents/',
  getParentRoute: () => rootRoute,
} as any)

const AdminUsersIndexRoute = AdminUsersIndexImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminLayoutRoute,
} as any)

const AdminTournamentsIndexRoute = AdminTournamentsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminTournamentsLayoutRoute,
} as any)

const AdminRatingIndexRoute = AdminRatingIndexImport.update({
  id: '/rating/',
  path: '/rating/',
  getParentRoute: () => AdminLayoutRoute,
} as any)

const AdminFeedbackIndexRoute = AdminFeedbackIndexImport.update({
  id: '/feedback/',
  path: '/feedback/',
  getParentRoute: () => AdminLayoutRoute,
} as any)

const AdminDashboardIndexRoute = AdminDashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminDashboardLayoutRoute,
} as any)

const AdminClubsIndexRoute = AdminClubsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminClubsLayoutRoute,
} as any)

const AdminBlogIndexRoute = AdminBlogIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminBlogLayoutRoute,
} as any)

const EpoodLitsentsSuccessRoute = EpoodLitsentsSuccessImport.update({
  id: '/epood/litsents/success',
  path: '/epood/litsents/success',
  getParentRoute: () => rootRoute,
} as any)

const EpoodLitsentsCancelRoute = EpoodLitsentsCancelImport.update({
  id: '/epood/litsents/cancel',
  path: '/epood/litsents/cancel',
  getParentRoute: () => rootRoute,
} as any)

const AdminTournamentsTournamentidLayoutRoute =
  AdminTournamentsTournamentidLayoutImport.update({
    id: '/$tournamentid',
    path: '/$tournamentid',
    getParentRoute: () => AdminTournamentsLayoutRoute,
  } as any)

const VoistlusedTournamentidTulemusedIndexRoute =
  VoistlusedTournamentidTulemusedIndexImport.update({
    id: '/tulemused/',
    path: '/tulemused/',
    getParentRoute: () => VoistlusedTournamentidLayoutRoute,
  } as any)

const VoistlusedTournamentidSponsoridIndexRoute =
  VoistlusedTournamentidSponsoridIndexImport.update({
    id: '/sponsorid/',
    path: '/sponsorid/',
    getParentRoute: () => VoistlusedTournamentidLayoutRoute,
  } as any)

const VoistlusedTournamentidMeediaIndexRoute =
  VoistlusedTournamentidMeediaIndexImport.update({
    id: '/meedia/',
    path: '/meedia/',
    getParentRoute: () => VoistlusedTournamentidLayoutRoute,
  } as any)

const VoistlusedTournamentidMangudIndexRoute =
  VoistlusedTournamentidMangudIndexImport.update({
    id: '/mangud/',
    path: '/mangud/',
    getParentRoute: () => VoistlusedTournamentidLayoutRoute,
  } as any)

const VoistlusedTournamentidMangijadIndexRoute =
  VoistlusedTournamentidMangijadIndexImport.update({
    id: '/mangijad/',
    path: '/mangijad/',
    getParentRoute: () => VoistlusedTournamentidLayoutRoute,
  } as any)

const VoistlusedTournamentidLauadIndexRoute =
  VoistlusedTournamentidLauadIndexImport.update({
    id: '/lauad/',
    path: '/lauad/',
    getParentRoute: () => VoistlusedTournamentidLayoutRoute,
  } as any)

const VoistlusedTournamentidKohadIndexRoute =
  VoistlusedTournamentidKohadIndexImport.update({
    id: '/kohad/',
    path: '/kohad/',
    getParentRoute: () => VoistlusedTournamentidLayoutRoute,
  } as any)

const VoistlusedTournamentidJuhendIndexRoute =
  VoistlusedTournamentidJuhendIndexImport.update({
    id: '/juhend/',
    path: '/juhend/',
    getParentRoute: () => VoistlusedTournamentidLayoutRoute,
  } as any)

const VoistlusedTournamentidGaleriiIndexRoute =
  VoistlusedTournamentidGaleriiIndexImport.update({
    id: '/galerii/',
    path: '/galerii/',
    getParentRoute: () => VoistlusedTournamentidLayoutRoute,
  } as any)

const VoistlusedTournamentidAjakavaIndexRoute =
  VoistlusedTournamentidAjakavaIndexImport.update({
    id: '/ajakava/',
    path: '/ajakava/',
    getParentRoute: () => VoistlusedTournamentidLayoutRoute,
  } as any)

const AdminTournamentsNewIndexRoute = AdminTournamentsNewIndexImport.update({
  id: '/new/',
  path: '/new/',
  getParentRoute: () => AdminTournamentsLayoutRoute,
} as any)

const AdminTournamentsTournamentidIndexRoute =
  AdminTournamentsTournamentidIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminTournamentsTournamentidLayoutRoute,
  } as any)

const AdminRatingTournamentidIndexRoute =
  AdminRatingTournamentidIndexImport.update({
    id: '/rating/$tournamentid/',
    path: '/rating/$tournamentid/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

const AdminBlogNewIndexRoute = AdminBlogNewIndexImport.update({
  id: '/new/',
  path: '/new/',
  getParentRoute: () => AdminBlogLayoutRoute,
} as any)

const AdminBlogBlogidIndexRoute = AdminBlogBlogidIndexImport.update({
  id: '/$blogid/',
  path: '/$blogid/',
  getParentRoute: () => AdminBlogLayoutRoute,
} as any)

const AdminTournamentsTournamentidAjakavaLayoutRoute =
  AdminTournamentsTournamentidAjakavaLayoutImport.update({
    id: '/ajakava',
    path: '/ajakava',
    getParentRoute: () => AdminTournamentsTournamentidLayoutRoute,
  } as any)

const VoistlusedTournamentidTulemusedGroupidIndexRoute =
  VoistlusedTournamentidTulemusedGroupidIndexImport.update({
    id: '/tulemused/$groupid/',
    path: '/tulemused/$groupid/',
    getParentRoute: () => VoistlusedTournamentidLayoutRoute,
  } as any)

const AdminTournamentsTournamentidPildidIndexRoute =
  AdminTournamentsTournamentidPildidIndexImport.update({
    id: '/pildid/',
    path: '/pildid/',
    getParentRoute: () => AdminTournamentsTournamentidLayoutRoute,
  } as any)

const AdminTournamentsTournamentidMangudIndexRoute =
  AdminTournamentsTournamentidMangudIndexImport.update({
    id: '/mangud/',
    path: '/mangud/',
    getParentRoute: () => AdminTournamentsTournamentidLayoutRoute,
  } as any)

const AdminTournamentsTournamentidGrupidIndexRoute =
  AdminTournamentsTournamentidGrupidIndexImport.update({
    id: '/grupid/',
    path: '/grupid/',
    getParentRoute: () => AdminTournamentsTournamentidLayoutRoute,
  } as any)

const AdminTournamentsTournamentidAjakavaIndexRoute =
  AdminTournamentsTournamentidAjakavaIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminTournamentsTournamentidAjakavaLayoutRoute,
  } as any)

const AdminTournamentsTournamentidGrupidGroupidLayoutRoute =
  AdminTournamentsTournamentidGrupidGroupidLayoutImport.update({
    id: '/grupid/$groupid',
    path: '/grupid/$groupid',
    getParentRoute: () => AdminTournamentsTournamentidLayoutRoute,
  } as any)

const AdminTournamentsTournamentidGrupidUusIndexRoute =
  AdminTournamentsTournamentidGrupidUusIndexImport.update({
    id: '/grupid/uus/',
    path: '/grupid/uus/',
    getParentRoute: () => AdminTournamentsTournamentidLayoutRoute,
  } as any)

const AdminTournamentsTournamentidGrupidGroupidIndexRoute =
  AdminTournamentsTournamentidGrupidGroupidIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminTournamentsTournamentidGrupidGroupidLayoutRoute,
  } as any)

const AdminTournamentsTournamentidAjakavaSeadedIndexRoute =
  AdminTournamentsTournamentidAjakavaSeadedIndexImport.update({
    id: '/seaded/',
    path: '/seaded/',
    getParentRoute: () => AdminTournamentsTournamentidAjakavaLayoutRoute,
  } as any)

const AdminTournamentsTournamentidGrupidGroupidTabelidIndexRoute =
  AdminTournamentsTournamentidGrupidGroupidTabelidIndexImport.update({
    id: '/tabelid/',
    path: '/tabelid/',
    getParentRoute: () => AdminTournamentsTournamentidGrupidGroupidLayoutRoute,
  } as any)

const AdminTournamentsTournamentidGrupidGroupidOsalejadIndexRoute =
  AdminTournamentsTournamentidGrupidGroupidOsalejadIndexImport.update({
    id: '/osalejad/',
    path: '/osalejad/',
    getParentRoute: () => AdminTournamentsTournamentidGrupidGroupidLayoutRoute,
  } as any)

const AdminTournamentsTournamentidGrupidGroupidMangudIndexRoute =
  AdminTournamentsTournamentidGrupidGroupidMangudIndexImport.update({
    id: '/mangud/',
    path: '/mangud/',
    getParentRoute: () => AdminTournamentsTournamentidGrupidGroupidLayoutRoute,
  } as any)

const AdminTournamentsTournamentidGrupidGroupidKohadIndexRoute =
  AdminTournamentsTournamentidGrupidGroupidKohadIndexImport.update({
    id: '/kohad/',
    path: '/kohad/',
    getParentRoute: () => AdminTournamentsTournamentidGrupidGroupidLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileLayoutImport
      parentRoute: typeof rootRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogLayoutImport
      parentRoute: typeof AdminLayoutImport
    }
    '/admin/clubs': {
      id: '/admin/clubs'
      path: '/clubs'
      fullPath: '/admin/clubs'
      preLoaderRoute: typeof AdminClubsLayoutImport
      parentRoute: typeof AdminLayoutImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardLayoutImport
      parentRoute: typeof AdminLayoutImport
    }
    '/admin/tournaments': {
      id: '/admin/tournaments'
      path: '/tournaments'
      fullPath: '/admin/tournaments'
      preLoaderRoute: typeof AdminTournamentsLayoutImport
      parentRoute: typeof AdminLayoutImport
    }
    '/voistlused/$tournamentid': {
      id: '/voistlused/$tournamentid'
      path: '/voistlused/$tournamentid'
      fullPath: '/voistlused/$tournamentid'
      preLoaderRoute: typeof VoistlusedTournamentidLayoutImport
      parentRoute: typeof rootRoute
    }
    '/uudised/$blogid': {
      id: '/uudised/$blogid'
      path: '/uudised/$blogid'
      fullPath: '/uudised/$blogid'
      preLoaderRoute: typeof UudisedBlogidImport
      parentRoute: typeof rootRoute
    }
    '/klubid/': {
      id: '/klubid/'
      path: '/klubid'
      fullPath: '/klubid'
      preLoaderRoute: typeof KlubidIndexImport
      parentRoute: typeof rootRoute
    }
    '/kontakt/': {
      id: '/kontakt/'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktIndexImport
      parentRoute: typeof rootRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexImport
      parentRoute: typeof ProfileLayoutImport
    }
    '/reeglid/': {
      id: '/reeglid/'
      path: '/reeglid'
      fullPath: '/reeglid'
      preLoaderRoute: typeof ReeglidIndexImport
      parentRoute: typeof rootRoute
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterIndexImport
      parentRoute: typeof rootRoute
    }
    '/reiting/': {
      id: '/reiting/'
      path: '/reiting'
      fullPath: '/reiting'
      preLoaderRoute: typeof ReitingIndexImport
      parentRoute: typeof rootRoute
    }
    '/tagasiside/': {
      id: '/tagasiside/'
      path: '/tagasiside'
      fullPath: '/tagasiside'
      preLoaderRoute: typeof TagasisideIndexImport
      parentRoute: typeof rootRoute
    }
    '/uudised/': {
      id: '/uudised/'
      path: '/uudised'
      fullPath: '/uudised'
      preLoaderRoute: typeof UudisedIndexImport
      parentRoute: typeof rootRoute
    }
    '/voistlused/': {
      id: '/voistlused/'
      path: '/voistlused'
      fullPath: '/voistlused'
      preLoaderRoute: typeof VoistlusedIndexImport
      parentRoute: typeof rootRoute
    }
    '/admin/tournaments/$tournamentid': {
      id: '/admin/tournaments/$tournamentid'
      path: '/$tournamentid'
      fullPath: '/admin/tournaments/$tournamentid'
      preLoaderRoute: typeof AdminTournamentsTournamentidLayoutImport
      parentRoute: typeof AdminTournamentsLayoutImport
    }
    '/epood/litsents/cancel': {
      id: '/epood/litsents/cancel'
      path: '/epood/litsents/cancel'
      fullPath: '/epood/litsents/cancel'
      preLoaderRoute: typeof EpoodLitsentsCancelImport
      parentRoute: typeof rootRoute
    }
    '/epood/litsents/success': {
      id: '/epood/litsents/success'
      path: '/epood/litsents/success'
      fullPath: '/epood/litsents/success'
      preLoaderRoute: typeof EpoodLitsentsSuccessImport
      parentRoute: typeof rootRoute
    }
    '/admin/blog/': {
      id: '/admin/blog/'
      path: '/'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AdminBlogIndexImport
      parentRoute: typeof AdminBlogLayoutImport
    }
    '/admin/clubs/': {
      id: '/admin/clubs/'
      path: '/'
      fullPath: '/admin/clubs/'
      preLoaderRoute: typeof AdminClubsIndexImport
      parentRoute: typeof AdminClubsLayoutImport
    }
    '/admin/dashboard/': {
      id: '/admin/dashboard/'
      path: '/'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof AdminDashboardIndexImport
      parentRoute: typeof AdminDashboardLayoutImport
    }
    '/admin/feedback/': {
      id: '/admin/feedback/'
      path: '/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminFeedbackIndexImport
      parentRoute: typeof AdminLayoutImport
    }
    '/admin/rating/': {
      id: '/admin/rating/'
      path: '/rating'
      fullPath: '/admin/rating'
      preLoaderRoute: typeof AdminRatingIndexImport
      parentRoute: typeof AdminLayoutImport
    }
    '/admin/tournaments/': {
      id: '/admin/tournaments/'
      path: '/'
      fullPath: '/admin/tournaments/'
      preLoaderRoute: typeof AdminTournamentsIndexImport
      parentRoute: typeof AdminTournamentsLayoutImport
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersIndexImport
      parentRoute: typeof AdminLayoutImport
    }
    '/epood/litsents/': {
      id: '/epood/litsents/'
      path: '/epood/litsents'
      fullPath: '/epood/litsents'
      preLoaderRoute: typeof EpoodLitsentsIndexImport
      parentRoute: typeof rootRoute
    }
    '/profile/settings/': {
      id: '/profile/settings/'
      path: '/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof ProfileSettingsIndexImport
      parentRoute: typeof ProfileLayoutImport
    }
    '/profile/tournaments/': {
      id: '/profile/tournaments/'
      path: '/tournaments'
      fullPath: '/profile/tournaments'
      preLoaderRoute: typeof ProfileTournamentsIndexImport
      parentRoute: typeof ProfileLayoutImport
    }
    '/voistlused/$tournamentid/': {
      id: '/voistlused/$tournamentid/'
      path: '/'
      fullPath: '/voistlused/$tournamentid/'
      preLoaderRoute: typeof VoistlusedTournamentidIndexImport
      parentRoute: typeof VoistlusedTournamentidLayoutImport
    }
    '/admin/tournaments/$tournamentid/ajakava': {
      id: '/admin/tournaments/$tournamentid/ajakava'
      path: '/ajakava'
      fullPath: '/admin/tournaments/$tournamentid/ajakava'
      preLoaderRoute: typeof AdminTournamentsTournamentidAjakavaLayoutImport
      parentRoute: typeof AdminTournamentsTournamentidLayoutImport
    }
    '/admin/blog/$blogid/': {
      id: '/admin/blog/$blogid/'
      path: '/$blogid'
      fullPath: '/admin/blog/$blogid'
      preLoaderRoute: typeof AdminBlogBlogidIndexImport
      parentRoute: typeof AdminBlogLayoutImport
    }
    '/admin/blog/new/': {
      id: '/admin/blog/new/'
      path: '/new'
      fullPath: '/admin/blog/new'
      preLoaderRoute: typeof AdminBlogNewIndexImport
      parentRoute: typeof AdminBlogLayoutImport
    }
    '/admin/rating/$tournamentid/': {
      id: '/admin/rating/$tournamentid/'
      path: '/rating/$tournamentid'
      fullPath: '/admin/rating/$tournamentid'
      preLoaderRoute: typeof AdminRatingTournamentidIndexImport
      parentRoute: typeof AdminLayoutImport
    }
    '/admin/tournaments/$tournamentid/': {
      id: '/admin/tournaments/$tournamentid/'
      path: '/'
      fullPath: '/admin/tournaments/$tournamentid/'
      preLoaderRoute: typeof AdminTournamentsTournamentidIndexImport
      parentRoute: typeof AdminTournamentsTournamentidLayoutImport
    }
    '/admin/tournaments/new/': {
      id: '/admin/tournaments/new/'
      path: '/new'
      fullPath: '/admin/tournaments/new'
      preLoaderRoute: typeof AdminTournamentsNewIndexImport
      parentRoute: typeof AdminTournamentsLayoutImport
    }
    '/voistlused/$tournamentid/ajakava/': {
      id: '/voistlused/$tournamentid/ajakava/'
      path: '/ajakava'
      fullPath: '/voistlused/$tournamentid/ajakava'
      preLoaderRoute: typeof VoistlusedTournamentidAjakavaIndexImport
      parentRoute: typeof VoistlusedTournamentidLayoutImport
    }
    '/voistlused/$tournamentid/galerii/': {
      id: '/voistlused/$tournamentid/galerii/'
      path: '/galerii'
      fullPath: '/voistlused/$tournamentid/galerii'
      preLoaderRoute: typeof VoistlusedTournamentidGaleriiIndexImport
      parentRoute: typeof VoistlusedTournamentidLayoutImport
    }
    '/voistlused/$tournamentid/juhend/': {
      id: '/voistlused/$tournamentid/juhend/'
      path: '/juhend'
      fullPath: '/voistlused/$tournamentid/juhend'
      preLoaderRoute: typeof VoistlusedTournamentidJuhendIndexImport
      parentRoute: typeof VoistlusedTournamentidLayoutImport
    }
    '/voistlused/$tournamentid/kohad/': {
      id: '/voistlused/$tournamentid/kohad/'
      path: '/kohad'
      fullPath: '/voistlused/$tournamentid/kohad'
      preLoaderRoute: typeof VoistlusedTournamentidKohadIndexImport
      parentRoute: typeof VoistlusedTournamentidLayoutImport
    }
    '/voistlused/$tournamentid/lauad/': {
      id: '/voistlused/$tournamentid/lauad/'
      path: '/lauad'
      fullPath: '/voistlused/$tournamentid/lauad'
      preLoaderRoute: typeof VoistlusedTournamentidLauadIndexImport
      parentRoute: typeof VoistlusedTournamentidLayoutImport
    }
    '/voistlused/$tournamentid/mangijad/': {
      id: '/voistlused/$tournamentid/mangijad/'
      path: '/mangijad'
      fullPath: '/voistlused/$tournamentid/mangijad'
      preLoaderRoute: typeof VoistlusedTournamentidMangijadIndexImport
      parentRoute: typeof VoistlusedTournamentidLayoutImport
    }
    '/voistlused/$tournamentid/mangud/': {
      id: '/voistlused/$tournamentid/mangud/'
      path: '/mangud'
      fullPath: '/voistlused/$tournamentid/mangud'
      preLoaderRoute: typeof VoistlusedTournamentidMangudIndexImport
      parentRoute: typeof VoistlusedTournamentidLayoutImport
    }
    '/voistlused/$tournamentid/meedia/': {
      id: '/voistlused/$tournamentid/meedia/'
      path: '/meedia'
      fullPath: '/voistlused/$tournamentid/meedia'
      preLoaderRoute: typeof VoistlusedTournamentidMeediaIndexImport
      parentRoute: typeof VoistlusedTournamentidLayoutImport
    }
    '/voistlused/$tournamentid/sponsorid/': {
      id: '/voistlused/$tournamentid/sponsorid/'
      path: '/sponsorid'
      fullPath: '/voistlused/$tournamentid/sponsorid'
      preLoaderRoute: typeof VoistlusedTournamentidSponsoridIndexImport
      parentRoute: typeof VoistlusedTournamentidLayoutImport
    }
    '/voistlused/$tournamentid/tulemused/': {
      id: '/voistlused/$tournamentid/tulemused/'
      path: '/tulemused'
      fullPath: '/voistlused/$tournamentid/tulemused'
      preLoaderRoute: typeof VoistlusedTournamentidTulemusedIndexImport
      parentRoute: typeof VoistlusedTournamentidLayoutImport
    }
    '/admin/tournaments/$tournamentid/grupid/$groupid': {
      id: '/admin/tournaments/$tournamentid/grupid/$groupid'
      path: '/grupid/$groupid'
      fullPath: '/admin/tournaments/$tournamentid/grupid/$groupid'
      preLoaderRoute: typeof AdminTournamentsTournamentidGrupidGroupidLayoutImport
      parentRoute: typeof AdminTournamentsTournamentidLayoutImport
    }
    '/admin/tournaments/$tournamentid/ajakava/': {
      id: '/admin/tournaments/$tournamentid/ajakava/'
      path: '/'
      fullPath: '/admin/tournaments/$tournamentid/ajakava/'
      preLoaderRoute: typeof AdminTournamentsTournamentidAjakavaIndexImport
      parentRoute: typeof AdminTournamentsTournamentidAjakavaLayoutImport
    }
    '/admin/tournaments/$tournamentid/grupid/': {
      id: '/admin/tournaments/$tournamentid/grupid/'
      path: '/grupid'
      fullPath: '/admin/tournaments/$tournamentid/grupid'
      preLoaderRoute: typeof AdminTournamentsTournamentidGrupidIndexImport
      parentRoute: typeof AdminTournamentsTournamentidLayoutImport
    }
    '/admin/tournaments/$tournamentid/mangud/': {
      id: '/admin/tournaments/$tournamentid/mangud/'
      path: '/mangud'
      fullPath: '/admin/tournaments/$tournamentid/mangud'
      preLoaderRoute: typeof AdminTournamentsTournamentidMangudIndexImport
      parentRoute: typeof AdminTournamentsTournamentidLayoutImport
    }
    '/admin/tournaments/$tournamentid/pildid/': {
      id: '/admin/tournaments/$tournamentid/pildid/'
      path: '/pildid'
      fullPath: '/admin/tournaments/$tournamentid/pildid'
      preLoaderRoute: typeof AdminTournamentsTournamentidPildidIndexImport
      parentRoute: typeof AdminTournamentsTournamentidLayoutImport
    }
    '/voistlused/$tournamentid/tulemused/$groupid/': {
      id: '/voistlused/$tournamentid/tulemused/$groupid/'
      path: '/tulemused/$groupid'
      fullPath: '/voistlused/$tournamentid/tulemused/$groupid'
      preLoaderRoute: typeof VoistlusedTournamentidTulemusedGroupidIndexImport
      parentRoute: typeof VoistlusedTournamentidLayoutImport
    }
    '/admin/tournaments/$tournamentid/ajakava/seaded/': {
      id: '/admin/tournaments/$tournamentid/ajakava/seaded/'
      path: '/seaded'
      fullPath: '/admin/tournaments/$tournamentid/ajakava/seaded'
      preLoaderRoute: typeof AdminTournamentsTournamentidAjakavaSeadedIndexImport
      parentRoute: typeof AdminTournamentsTournamentidAjakavaLayoutImport
    }
    '/admin/tournaments/$tournamentid/grupid/$groupid/': {
      id: '/admin/tournaments/$tournamentid/grupid/$groupid/'
      path: '/'
      fullPath: '/admin/tournaments/$tournamentid/grupid/$groupid/'
      preLoaderRoute: typeof AdminTournamentsTournamentidGrupidGroupidIndexImport
      parentRoute: typeof AdminTournamentsTournamentidGrupidGroupidLayoutImport
    }
    '/admin/tournaments/$tournamentid/grupid/uus/': {
      id: '/admin/tournaments/$tournamentid/grupid/uus/'
      path: '/grupid/uus'
      fullPath: '/admin/tournaments/$tournamentid/grupid/uus'
      preLoaderRoute: typeof AdminTournamentsTournamentidGrupidUusIndexImport
      parentRoute: typeof AdminTournamentsTournamentidLayoutImport
    }
    '/admin/tournaments/$tournamentid/grupid/$groupid/kohad/': {
      id: '/admin/tournaments/$tournamentid/grupid/$groupid/kohad/'
      path: '/kohad'
      fullPath: '/admin/tournaments/$tournamentid/grupid/$groupid/kohad'
      preLoaderRoute: typeof AdminTournamentsTournamentidGrupidGroupidKohadIndexImport
      parentRoute: typeof AdminTournamentsTournamentidGrupidGroupidLayoutImport
    }
    '/admin/tournaments/$tournamentid/grupid/$groupid/mangud/': {
      id: '/admin/tournaments/$tournamentid/grupid/$groupid/mangud/'
      path: '/mangud'
      fullPath: '/admin/tournaments/$tournamentid/grupid/$groupid/mangud'
      preLoaderRoute: typeof AdminTournamentsTournamentidGrupidGroupidMangudIndexImport
      parentRoute: typeof AdminTournamentsTournamentidGrupidGroupidLayoutImport
    }
    '/admin/tournaments/$tournamentid/grupid/$groupid/osalejad/': {
      id: '/admin/tournaments/$tournamentid/grupid/$groupid/osalejad/'
      path: '/osalejad'
      fullPath: '/admin/tournaments/$tournamentid/grupid/$groupid/osalejad'
      preLoaderRoute: typeof AdminTournamentsTournamentidGrupidGroupidOsalejadIndexImport
      parentRoute: typeof AdminTournamentsTournamentidGrupidGroupidLayoutImport
    }
    '/admin/tournaments/$tournamentid/grupid/$groupid/tabelid/': {
      id: '/admin/tournaments/$tournamentid/grupid/$groupid/tabelid/'
      path: '/tabelid'
      fullPath: '/admin/tournaments/$tournamentid/grupid/$groupid/tabelid'
      preLoaderRoute: typeof AdminTournamentsTournamentidGrupidGroupidTabelidIndexImport
      parentRoute: typeof AdminTournamentsTournamentidGrupidGroupidLayoutImport
    }
  }
}

// Create and export the route tree

interface AdminBlogLayoutRouteChildren {
  AdminBlogIndexRoute: typeof AdminBlogIndexRoute
  AdminBlogBlogidIndexRoute: typeof AdminBlogBlogidIndexRoute
  AdminBlogNewIndexRoute: typeof AdminBlogNewIndexRoute
}

const AdminBlogLayoutRouteChildren: AdminBlogLayoutRouteChildren = {
  AdminBlogIndexRoute: AdminBlogIndexRoute,
  AdminBlogBlogidIndexRoute: AdminBlogBlogidIndexRoute,
  AdminBlogNewIndexRoute: AdminBlogNewIndexRoute,
}

const AdminBlogLayoutRouteWithChildren = AdminBlogLayoutRoute._addFileChildren(
  AdminBlogLayoutRouteChildren,
)

interface AdminClubsLayoutRouteChildren {
  AdminClubsIndexRoute: typeof AdminClubsIndexRoute
}

const AdminClubsLayoutRouteChildren: AdminClubsLayoutRouteChildren = {
  AdminClubsIndexRoute: AdminClubsIndexRoute,
}

const AdminClubsLayoutRouteWithChildren =
  AdminClubsLayoutRoute._addFileChildren(AdminClubsLayoutRouteChildren)

interface AdminDashboardLayoutRouteChildren {
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
}

const AdminDashboardLayoutRouteChildren: AdminDashboardLayoutRouteChildren = {
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
}

const AdminDashboardLayoutRouteWithChildren =
  AdminDashboardLayoutRoute._addFileChildren(AdminDashboardLayoutRouteChildren)

interface AdminTournamentsTournamentidAjakavaLayoutRouteChildren {
  AdminTournamentsTournamentidAjakavaIndexRoute: typeof AdminTournamentsTournamentidAjakavaIndexRoute
  AdminTournamentsTournamentidAjakavaSeadedIndexRoute: typeof AdminTournamentsTournamentidAjakavaSeadedIndexRoute
}

const AdminTournamentsTournamentidAjakavaLayoutRouteChildren: AdminTournamentsTournamentidAjakavaLayoutRouteChildren =
  {
    AdminTournamentsTournamentidAjakavaIndexRoute:
      AdminTournamentsTournamentidAjakavaIndexRoute,
    AdminTournamentsTournamentidAjakavaSeadedIndexRoute:
      AdminTournamentsTournamentidAjakavaSeadedIndexRoute,
  }

const AdminTournamentsTournamentidAjakavaLayoutRouteWithChildren =
  AdminTournamentsTournamentidAjakavaLayoutRoute._addFileChildren(
    AdminTournamentsTournamentidAjakavaLayoutRouteChildren,
  )

interface AdminTournamentsTournamentidGrupidGroupidLayoutRouteChildren {
  AdminTournamentsTournamentidGrupidGroupidIndexRoute: typeof AdminTournamentsTournamentidGrupidGroupidIndexRoute
  AdminTournamentsTournamentidGrupidGroupidKohadIndexRoute: typeof AdminTournamentsTournamentidGrupidGroupidKohadIndexRoute
  AdminTournamentsTournamentidGrupidGroupidMangudIndexRoute: typeof AdminTournamentsTournamentidGrupidGroupidMangudIndexRoute
  AdminTournamentsTournamentidGrupidGroupidOsalejadIndexRoute: typeof AdminTournamentsTournamentidGrupidGroupidOsalejadIndexRoute
  AdminTournamentsTournamentidGrupidGroupidTabelidIndexRoute: typeof AdminTournamentsTournamentidGrupidGroupidTabelidIndexRoute
}

const AdminTournamentsTournamentidGrupidGroupidLayoutRouteChildren: AdminTournamentsTournamentidGrupidGroupidLayoutRouteChildren =
  {
    AdminTournamentsTournamentidGrupidGroupidIndexRoute:
      AdminTournamentsTournamentidGrupidGroupidIndexRoute,
    AdminTournamentsTournamentidGrupidGroupidKohadIndexRoute:
      AdminTournamentsTournamentidGrupidGroupidKohadIndexRoute,
    AdminTournamentsTournamentidGrupidGroupidMangudIndexRoute:
      AdminTournamentsTournamentidGrupidGroupidMangudIndexRoute,
    AdminTournamentsTournamentidGrupidGroupidOsalejadIndexRoute:
      AdminTournamentsTournamentidGrupidGroupidOsalejadIndexRoute,
    AdminTournamentsTournamentidGrupidGroupidTabelidIndexRoute:
      AdminTournamentsTournamentidGrupidGroupidTabelidIndexRoute,
  }

const AdminTournamentsTournamentidGrupidGroupidLayoutRouteWithChildren =
  AdminTournamentsTournamentidGrupidGroupidLayoutRoute._addFileChildren(
    AdminTournamentsTournamentidGrupidGroupidLayoutRouteChildren,
  )

interface AdminTournamentsTournamentidLayoutRouteChildren {
  AdminTournamentsTournamentidAjakavaLayoutRoute: typeof AdminTournamentsTournamentidAjakavaLayoutRouteWithChildren
  AdminTournamentsTournamentidIndexRoute: typeof AdminTournamentsTournamentidIndexRoute
  AdminTournamentsTournamentidGrupidGroupidLayoutRoute: typeof AdminTournamentsTournamentidGrupidGroupidLayoutRouteWithChildren
  AdminTournamentsTournamentidGrupidIndexRoute: typeof AdminTournamentsTournamentidGrupidIndexRoute
  AdminTournamentsTournamentidMangudIndexRoute: typeof AdminTournamentsTournamentidMangudIndexRoute
  AdminTournamentsTournamentidPildidIndexRoute: typeof AdminTournamentsTournamentidPildidIndexRoute
  AdminTournamentsTournamentidGrupidUusIndexRoute: typeof AdminTournamentsTournamentidGrupidUusIndexRoute
}

const AdminTournamentsTournamentidLayoutRouteChildren: AdminTournamentsTournamentidLayoutRouteChildren =
  {
    AdminTournamentsTournamentidAjakavaLayoutRoute:
      AdminTournamentsTournamentidAjakavaLayoutRouteWithChildren,
    AdminTournamentsTournamentidIndexRoute:
      AdminTournamentsTournamentidIndexRoute,
    AdminTournamentsTournamentidGrupidGroupidLayoutRoute:
      AdminTournamentsTournamentidGrupidGroupidLayoutRouteWithChildren,
    AdminTournamentsTournamentidGrupidIndexRoute:
      AdminTournamentsTournamentidGrupidIndexRoute,
    AdminTournamentsTournamentidMangudIndexRoute:
      AdminTournamentsTournamentidMangudIndexRoute,
    AdminTournamentsTournamentidPildidIndexRoute:
      AdminTournamentsTournamentidPildidIndexRoute,
    AdminTournamentsTournamentidGrupidUusIndexRoute:
      AdminTournamentsTournamentidGrupidUusIndexRoute,
  }

const AdminTournamentsTournamentidLayoutRouteWithChildren =
  AdminTournamentsTournamentidLayoutRoute._addFileChildren(
    AdminTournamentsTournamentidLayoutRouteChildren,
  )

interface AdminTournamentsLayoutRouteChildren {
  AdminTournamentsTournamentidLayoutRoute: typeof AdminTournamentsTournamentidLayoutRouteWithChildren
  AdminTournamentsIndexRoute: typeof AdminTournamentsIndexRoute
  AdminTournamentsNewIndexRoute: typeof AdminTournamentsNewIndexRoute
}

const AdminTournamentsLayoutRouteChildren: AdminTournamentsLayoutRouteChildren =
  {
    AdminTournamentsTournamentidLayoutRoute:
      AdminTournamentsTournamentidLayoutRouteWithChildren,
    AdminTournamentsIndexRoute: AdminTournamentsIndexRoute,
    AdminTournamentsNewIndexRoute: AdminTournamentsNewIndexRoute,
  }

const AdminTournamentsLayoutRouteWithChildren =
  AdminTournamentsLayoutRoute._addFileChildren(
    AdminTournamentsLayoutRouteChildren,
  )

interface AdminLayoutRouteChildren {
  AdminBlogLayoutRoute: typeof AdminBlogLayoutRouteWithChildren
  AdminClubsLayoutRoute: typeof AdminClubsLayoutRouteWithChildren
  AdminDashboardLayoutRoute: typeof AdminDashboardLayoutRouteWithChildren
  AdminTournamentsLayoutRoute: typeof AdminTournamentsLayoutRouteWithChildren
  AdminFeedbackIndexRoute: typeof AdminFeedbackIndexRoute
  AdminRatingIndexRoute: typeof AdminRatingIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminRatingTournamentidIndexRoute: typeof AdminRatingTournamentidIndexRoute
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminBlogLayoutRoute: AdminBlogLayoutRouteWithChildren,
  AdminClubsLayoutRoute: AdminClubsLayoutRouteWithChildren,
  AdminDashboardLayoutRoute: AdminDashboardLayoutRouteWithChildren,
  AdminTournamentsLayoutRoute: AdminTournamentsLayoutRouteWithChildren,
  AdminFeedbackIndexRoute: AdminFeedbackIndexRoute,
  AdminRatingIndexRoute: AdminRatingIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminRatingTournamentidIndexRoute: AdminRatingTournamentidIndexRoute,
}

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(
  AdminLayoutRouteChildren,
)

interface ProfileLayoutRouteChildren {
  ProfileIndexRoute: typeof ProfileIndexRoute
  ProfileSettingsIndexRoute: typeof ProfileSettingsIndexRoute
  ProfileTournamentsIndexRoute: typeof ProfileTournamentsIndexRoute
}

const ProfileLayoutRouteChildren: ProfileLayoutRouteChildren = {
  ProfileIndexRoute: ProfileIndexRoute,
  ProfileSettingsIndexRoute: ProfileSettingsIndexRoute,
  ProfileTournamentsIndexRoute: ProfileTournamentsIndexRoute,
}

const ProfileLayoutRouteWithChildren = ProfileLayoutRoute._addFileChildren(
  ProfileLayoutRouteChildren,
)

interface VoistlusedTournamentidLayoutRouteChildren {
  VoistlusedTournamentidIndexRoute: typeof VoistlusedTournamentidIndexRoute
  VoistlusedTournamentidAjakavaIndexRoute: typeof VoistlusedTournamentidAjakavaIndexRoute
  VoistlusedTournamentidGaleriiIndexRoute: typeof VoistlusedTournamentidGaleriiIndexRoute
  VoistlusedTournamentidJuhendIndexRoute: typeof VoistlusedTournamentidJuhendIndexRoute
  VoistlusedTournamentidKohadIndexRoute: typeof VoistlusedTournamentidKohadIndexRoute
  VoistlusedTournamentidLauadIndexRoute: typeof VoistlusedTournamentidLauadIndexRoute
  VoistlusedTournamentidMangijadIndexRoute: typeof VoistlusedTournamentidMangijadIndexRoute
  VoistlusedTournamentidMangudIndexRoute: typeof VoistlusedTournamentidMangudIndexRoute
  VoistlusedTournamentidMeediaIndexRoute: typeof VoistlusedTournamentidMeediaIndexRoute
  VoistlusedTournamentidSponsoridIndexRoute: typeof VoistlusedTournamentidSponsoridIndexRoute
  VoistlusedTournamentidTulemusedIndexRoute: typeof VoistlusedTournamentidTulemusedIndexRoute
  VoistlusedTournamentidTulemusedGroupidIndexRoute: typeof VoistlusedTournamentidTulemusedGroupidIndexRoute
}

const VoistlusedTournamentidLayoutRouteChildren: VoistlusedTournamentidLayoutRouteChildren =
  {
    VoistlusedTournamentidIndexRoute: VoistlusedTournamentidIndexRoute,
    VoistlusedTournamentidAjakavaIndexRoute:
      VoistlusedTournamentidAjakavaIndexRoute,
    VoistlusedTournamentidGaleriiIndexRoute:
      VoistlusedTournamentidGaleriiIndexRoute,
    VoistlusedTournamentidJuhendIndexRoute:
      VoistlusedTournamentidJuhendIndexRoute,
    VoistlusedTournamentidKohadIndexRoute:
      VoistlusedTournamentidKohadIndexRoute,
    VoistlusedTournamentidLauadIndexRoute:
      VoistlusedTournamentidLauadIndexRoute,
    VoistlusedTournamentidMangijadIndexRoute:
      VoistlusedTournamentidMangijadIndexRoute,
    VoistlusedTournamentidMangudIndexRoute:
      VoistlusedTournamentidMangudIndexRoute,
    VoistlusedTournamentidMeediaIndexRoute:
      VoistlusedTournamentidMeediaIndexRoute,
    VoistlusedTournamentidSponsoridIndexRoute:
      VoistlusedTournamentidSponsoridIndexRoute,
    VoistlusedTournamentidTulemusedIndexRoute:
      VoistlusedTournamentidTulemusedIndexRoute,
    VoistlusedTournamentidTulemusedGroupidIndexRoute:
      VoistlusedTournamentidTulemusedGroupidIndexRoute,
  }

const VoistlusedTournamentidLayoutRouteWithChildren =
  VoistlusedTournamentidLayoutRoute._addFileChildren(
    VoistlusedTournamentidLayoutRouteChildren,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminLayoutRouteWithChildren
  '/profile': typeof ProfileLayoutRouteWithChildren
  '/admin/blog': typeof AdminBlogLayoutRouteWithChildren
  '/admin/clubs': typeof AdminClubsLayoutRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardLayoutRouteWithChildren
  '/admin/tournaments': typeof AdminTournamentsLayoutRouteWithChildren
  '/voistlused/$tournamentid': typeof VoistlusedTournamentidLayoutRouteWithChildren
  '/uudised/$blogid': typeof UudisedBlogidRoute
  '/klubid': typeof KlubidIndexRoute
  '/kontakt': typeof KontaktIndexRoute
  '/login': typeof LoginIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/reeglid': typeof ReeglidIndexRoute
  '/register': typeof RegisterIndexRoute
  '/reiting': typeof ReitingIndexRoute
  '/tagasiside': typeof TagasisideIndexRoute
  '/uudised': typeof UudisedIndexRoute
  '/voistlused': typeof VoistlusedIndexRoute
  '/admin/tournaments/$tournamentid': typeof AdminTournamentsTournamentidLayoutRouteWithChildren
  '/epood/litsents/cancel': typeof EpoodLitsentsCancelRoute
  '/epood/litsents/success': typeof EpoodLitsentsSuccessRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/clubs/': typeof AdminClubsIndexRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/admin/feedback': typeof AdminFeedbackIndexRoute
  '/admin/rating': typeof AdminRatingIndexRoute
  '/admin/tournaments/': typeof AdminTournamentsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/epood/litsents': typeof EpoodLitsentsIndexRoute
  '/profile/settings': typeof ProfileSettingsIndexRoute
  '/profile/tournaments': typeof ProfileTournamentsIndexRoute
  '/voistlused/$tournamentid/': typeof VoistlusedTournamentidIndexRoute
  '/admin/tournaments/$tournamentid/ajakava': typeof AdminTournamentsTournamentidAjakavaLayoutRouteWithChildren
  '/admin/blog/$blogid': typeof AdminBlogBlogidIndexRoute
  '/admin/blog/new': typeof AdminBlogNewIndexRoute
  '/admin/rating/$tournamentid': typeof AdminRatingTournamentidIndexRoute
  '/admin/tournaments/$tournamentid/': typeof AdminTournamentsTournamentidIndexRoute
  '/admin/tournaments/new': typeof AdminTournamentsNewIndexRoute
  '/voistlused/$tournamentid/ajakava': typeof VoistlusedTournamentidAjakavaIndexRoute
  '/voistlused/$tournamentid/galerii': typeof VoistlusedTournamentidGaleriiIndexRoute
  '/voistlused/$tournamentid/juhend': typeof VoistlusedTournamentidJuhendIndexRoute
  '/voistlused/$tournamentid/kohad': typeof VoistlusedTournamentidKohadIndexRoute
  '/voistlused/$tournamentid/lauad': typeof VoistlusedTournamentidLauadIndexRoute
  '/voistlused/$tournamentid/mangijad': typeof VoistlusedTournamentidMangijadIndexRoute
  '/voistlused/$tournamentid/mangud': typeof VoistlusedTournamentidMangudIndexRoute
  '/voistlused/$tournamentid/meedia': typeof VoistlusedTournamentidMeediaIndexRoute
  '/voistlused/$tournamentid/sponsorid': typeof VoistlusedTournamentidSponsoridIndexRoute
  '/voistlused/$tournamentid/tulemused': typeof VoistlusedTournamentidTulemusedIndexRoute
  '/admin/tournaments/$tournamentid/grupid/$groupid': typeof AdminTournamentsTournamentidGrupidGroupidLayoutRouteWithChildren
  '/admin/tournaments/$tournamentid/ajakava/': typeof AdminTournamentsTournamentidAjakavaIndexRoute
  '/admin/tournaments/$tournamentid/grupid': typeof AdminTournamentsTournamentidGrupidIndexRoute
  '/admin/tournaments/$tournamentid/mangud': typeof AdminTournamentsTournamentidMangudIndexRoute
  '/admin/tournaments/$tournamentid/pildid': typeof AdminTournamentsTournamentidPildidIndexRoute
  '/voistlused/$tournamentid/tulemused/$groupid': typeof VoistlusedTournamentidTulemusedGroupidIndexRoute
  '/admin/tournaments/$tournamentid/ajakava/seaded': typeof AdminTournamentsTournamentidAjakavaSeadedIndexRoute
  '/admin/tournaments/$tournamentid/grupid/$groupid/': typeof AdminTournamentsTournamentidGrupidGroupidIndexRoute
  '/admin/tournaments/$tournamentid/grupid/uus': typeof AdminTournamentsTournamentidGrupidUusIndexRoute
  '/admin/tournaments/$tournamentid/grupid/$groupid/kohad': typeof AdminTournamentsTournamentidGrupidGroupidKohadIndexRoute
  '/admin/tournaments/$tournamentid/grupid/$groupid/mangud': typeof AdminTournamentsTournamentidGrupidGroupidMangudIndexRoute
  '/admin/tournaments/$tournamentid/grupid/$groupid/osalejad': typeof AdminTournamentsTournamentidGrupidGroupidOsalejadIndexRoute
  '/admin/tournaments/$tournamentid/grupid/$groupid/tabelid': typeof AdminTournamentsTournamentidGrupidGroupidTabelidIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminLayoutRouteWithChildren
  '/uudised/$blogid': typeof UudisedBlogidRoute
  '/klubid': typeof KlubidIndexRoute
  '/kontakt': typeof KontaktIndexRoute
  '/login': typeof LoginIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/reeglid': typeof ReeglidIndexRoute
  '/register': typeof RegisterIndexRoute
  '/reiting': typeof ReitingIndexRoute
  '/tagasiside': typeof TagasisideIndexRoute
  '/uudised': typeof UudisedIndexRoute
  '/voistlused': typeof VoistlusedIndexRoute
  '/epood/litsents/cancel': typeof EpoodLitsentsCancelRoute
  '/epood/litsents/success': typeof EpoodLitsentsSuccessRoute
  '/admin/blog': typeof AdminBlogIndexRoute
  '/admin/clubs': typeof AdminClubsIndexRoute
  '/admin/dashboard': typeof AdminDashboardIndexRoute
  '/admin/feedback': typeof AdminFeedbackIndexRoute
  '/admin/rating': typeof AdminRatingIndexRoute
  '/admin/tournaments': typeof AdminTournamentsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/epood/litsents': typeof EpoodLitsentsIndexRoute
  '/profile/settings': typeof ProfileSettingsIndexRoute
  '/profile/tournaments': typeof ProfileTournamentsIndexRoute
  '/voistlused/$tournamentid': typeof VoistlusedTournamentidIndexRoute
  '/admin/blog/$blogid': typeof AdminBlogBlogidIndexRoute
  '/admin/blog/new': typeof AdminBlogNewIndexRoute
  '/admin/rating/$tournamentid': typeof AdminRatingTournamentidIndexRoute
  '/admin/tournaments/$tournamentid': typeof AdminTournamentsTournamentidIndexRoute
  '/admin/tournaments/new': typeof AdminTournamentsNewIndexRoute
  '/voistlused/$tournamentid/ajakava': typeof VoistlusedTournamentidAjakavaIndexRoute
  '/voistlused/$tournamentid/galerii': typeof VoistlusedTournamentidGaleriiIndexRoute
  '/voistlused/$tournamentid/juhend': typeof VoistlusedTournamentidJuhendIndexRoute
  '/voistlused/$tournamentid/kohad': typeof VoistlusedTournamentidKohadIndexRoute
  '/voistlused/$tournamentid/lauad': typeof VoistlusedTournamentidLauadIndexRoute
  '/voistlused/$tournamentid/mangijad': typeof VoistlusedTournamentidMangijadIndexRoute
  '/voistlused/$tournamentid/mangud': typeof VoistlusedTournamentidMangudIndexRoute
  '/voistlused/$tournamentid/meedia': typeof VoistlusedTournamentidMeediaIndexRoute
  '/voistlused/$tournamentid/sponsorid': typeof VoistlusedTournamentidSponsoridIndexRoute
  '/voistlused/$tournamentid/tulemused': typeof VoistlusedTournamentidTulemusedIndexRoute
  '/admin/tournaments/$tournamentid/ajakava': typeof AdminTournamentsTournamentidAjakavaIndexRoute
  '/admin/tournaments/$tournamentid/grupid': typeof AdminTournamentsTournamentidGrupidIndexRoute
  '/admin/tournaments/$tournamentid/mangud': typeof AdminTournamentsTournamentidMangudIndexRoute
  '/admin/tournaments/$tournamentid/pildid': typeof AdminTournamentsTournamentidPildidIndexRoute
  '/voistlused/$tournamentid/tulemused/$groupid': typeof VoistlusedTournamentidTulemusedGroupidIndexRoute
  '/admin/tournaments/$tournamentid/ajakava/seaded': typeof AdminTournamentsTournamentidAjakavaSeadedIndexRoute
  '/admin/tournaments/$tournamentid/grupid/$groupid': typeof AdminTournamentsTournamentidGrupidGroupidIndexRoute
  '/admin/tournaments/$tournamentid/grupid/uus': typeof AdminTournamentsTournamentidGrupidUusIndexRoute
  '/admin/tournaments/$tournamentid/grupid/$groupid/kohad': typeof AdminTournamentsTournamentidGrupidGroupidKohadIndexRoute
  '/admin/tournaments/$tournamentid/grupid/$groupid/mangud': typeof AdminTournamentsTournamentidGrupidGroupidMangudIndexRoute
  '/admin/tournaments/$tournamentid/grupid/$groupid/osalejad': typeof AdminTournamentsTournamentidGrupidGroupidOsalejadIndexRoute
  '/admin/tournaments/$tournamentid/grupid/$groupid/tabelid': typeof AdminTournamentsTournamentidGrupidGroupidTabelidIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/admin': typeof AdminLayoutRouteWithChildren
  '/profile': typeof ProfileLayoutRouteWithChildren
  '/admin/blog': typeof AdminBlogLayoutRouteWithChildren
  '/admin/clubs': typeof AdminClubsLayoutRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardLayoutRouteWithChildren
  '/admin/tournaments': typeof AdminTournamentsLayoutRouteWithChildren
  '/voistlused/$tournamentid': typeof VoistlusedTournamentidLayoutRouteWithChildren
  '/uudised/$blogid': typeof UudisedBlogidRoute
  '/klubid/': typeof KlubidIndexRoute
  '/kontakt/': typeof KontaktIndexRoute
  '/login/': typeof LoginIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/reeglid/': typeof ReeglidIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/reiting/': typeof ReitingIndexRoute
  '/tagasiside/': typeof TagasisideIndexRoute
  '/uudised/': typeof UudisedIndexRoute
  '/voistlused/': typeof VoistlusedIndexRoute
  '/admin/tournaments/$tournamentid': typeof AdminTournamentsTournamentidLayoutRouteWithChildren
  '/epood/litsents/cancel': typeof EpoodLitsentsCancelRoute
  '/epood/litsents/success': typeof EpoodLitsentsSuccessRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/clubs/': typeof AdminClubsIndexRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/admin/feedback/': typeof AdminFeedbackIndexRoute
  '/admin/rating/': typeof AdminRatingIndexRoute
  '/admin/tournaments/': typeof AdminTournamentsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/epood/litsents/': typeof EpoodLitsentsIndexRoute
  '/profile/settings/': typeof ProfileSettingsIndexRoute
  '/profile/tournaments/': typeof ProfileTournamentsIndexRoute
  '/voistlused/$tournamentid/': typeof VoistlusedTournamentidIndexRoute
  '/admin/tournaments/$tournamentid/ajakava': typeof AdminTournamentsTournamentidAjakavaLayoutRouteWithChildren
  '/admin/blog/$blogid/': typeof AdminBlogBlogidIndexRoute
  '/admin/blog/new/': typeof AdminBlogNewIndexRoute
  '/admin/rating/$tournamentid/': typeof AdminRatingTournamentidIndexRoute
  '/admin/tournaments/$tournamentid/': typeof AdminTournamentsTournamentidIndexRoute
  '/admin/tournaments/new/': typeof AdminTournamentsNewIndexRoute
  '/voistlused/$tournamentid/ajakava/': typeof VoistlusedTournamentidAjakavaIndexRoute
  '/voistlused/$tournamentid/galerii/': typeof VoistlusedTournamentidGaleriiIndexRoute
  '/voistlused/$tournamentid/juhend/': typeof VoistlusedTournamentidJuhendIndexRoute
  '/voistlused/$tournamentid/kohad/': typeof VoistlusedTournamentidKohadIndexRoute
  '/voistlused/$tournamentid/lauad/': typeof VoistlusedTournamentidLauadIndexRoute
  '/voistlused/$tournamentid/mangijad/': typeof VoistlusedTournamentidMangijadIndexRoute
  '/voistlused/$tournamentid/mangud/': typeof VoistlusedTournamentidMangudIndexRoute
  '/voistlused/$tournamentid/meedia/': typeof VoistlusedTournamentidMeediaIndexRoute
  '/voistlused/$tournamentid/sponsorid/': typeof VoistlusedTournamentidSponsoridIndexRoute
  '/voistlused/$tournamentid/tulemused/': typeof VoistlusedTournamentidTulemusedIndexRoute
  '/admin/tournaments/$tournamentid/grupid/$groupid': typeof AdminTournamentsTournamentidGrupidGroupidLayoutRouteWithChildren
  '/admin/tournaments/$tournamentid/ajakava/': typeof AdminTournamentsTournamentidAjakavaIndexRoute
  '/admin/tournaments/$tournamentid/grupid/': typeof AdminTournamentsTournamentidGrupidIndexRoute
  '/admin/tournaments/$tournamentid/mangud/': typeof AdminTournamentsTournamentidMangudIndexRoute
  '/admin/tournaments/$tournamentid/pildid/': typeof AdminTournamentsTournamentidPildidIndexRoute
  '/voistlused/$tournamentid/tulemused/$groupid/': typeof VoistlusedTournamentidTulemusedGroupidIndexRoute
  '/admin/tournaments/$tournamentid/ajakava/seaded/': typeof AdminTournamentsTournamentidAjakavaSeadedIndexRoute
  '/admin/tournaments/$tournamentid/grupid/$groupid/': typeof AdminTournamentsTournamentidGrupidGroupidIndexRoute
  '/admin/tournaments/$tournamentid/grupid/uus/': typeof AdminTournamentsTournamentidGrupidUusIndexRoute
  '/admin/tournaments/$tournamentid/grupid/$groupid/kohad/': typeof AdminTournamentsTournamentidGrupidGroupidKohadIndexRoute
  '/admin/tournaments/$tournamentid/grupid/$groupid/mangud/': typeof AdminTournamentsTournamentidGrupidGroupidMangudIndexRoute
  '/admin/tournaments/$tournamentid/grupid/$groupid/osalejad/': typeof AdminTournamentsTournamentidGrupidGroupidOsalejadIndexRoute
  '/admin/tournaments/$tournamentid/grupid/$groupid/tabelid/': typeof AdminTournamentsTournamentidGrupidGroupidTabelidIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/profile'
    | '/admin/blog'
    | '/admin/clubs'
    | '/admin/dashboard'
    | '/admin/tournaments'
    | '/voistlused/$tournamentid'
    | '/uudised/$blogid'
    | '/klubid'
    | '/kontakt'
    | '/login'
    | '/profile/'
    | '/reeglid'
    | '/register'
    | '/reiting'
    | '/tagasiside'
    | '/uudised'
    | '/voistlused'
    | '/admin/tournaments/$tournamentid'
    | '/epood/litsents/cancel'
    | '/epood/litsents/success'
    | '/admin/blog/'
    | '/admin/clubs/'
    | '/admin/dashboard/'
    | '/admin/feedback'
    | '/admin/rating'
    | '/admin/tournaments/'
    | '/admin/users'
    | '/epood/litsents'
    | '/profile/settings'
    | '/profile/tournaments'
    | '/voistlused/$tournamentid/'
    | '/admin/tournaments/$tournamentid/ajakava'
    | '/admin/blog/$blogid'
    | '/admin/blog/new'
    | '/admin/rating/$tournamentid'
    | '/admin/tournaments/$tournamentid/'
    | '/admin/tournaments/new'
    | '/voistlused/$tournamentid/ajakava'
    | '/voistlused/$tournamentid/galerii'
    | '/voistlused/$tournamentid/juhend'
    | '/voistlused/$tournamentid/kohad'
    | '/voistlused/$tournamentid/lauad'
    | '/voistlused/$tournamentid/mangijad'
    | '/voistlused/$tournamentid/mangud'
    | '/voistlused/$tournamentid/meedia'
    | '/voistlused/$tournamentid/sponsorid'
    | '/voistlused/$tournamentid/tulemused'
    | '/admin/tournaments/$tournamentid/grupid/$groupid'
    | '/admin/tournaments/$tournamentid/ajakava/'
    | '/admin/tournaments/$tournamentid/grupid'
    | '/admin/tournaments/$tournamentid/mangud'
    | '/admin/tournaments/$tournamentid/pildid'
    | '/voistlused/$tournamentid/tulemused/$groupid'
    | '/admin/tournaments/$tournamentid/ajakava/seaded'
    | '/admin/tournaments/$tournamentid/grupid/$groupid/'
    | '/admin/tournaments/$tournamentid/grupid/uus'
    | '/admin/tournaments/$tournamentid/grupid/$groupid/kohad'
    | '/admin/tournaments/$tournamentid/grupid/$groupid/mangud'
    | '/admin/tournaments/$tournamentid/grupid/$groupid/osalejad'
    | '/admin/tournaments/$tournamentid/grupid/$groupid/tabelid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/uudised/$blogid'
    | '/klubid'
    | '/kontakt'
    | '/login'
    | '/profile'
    | '/reeglid'
    | '/register'
    | '/reiting'
    | '/tagasiside'
    | '/uudised'
    | '/voistlused'
    | '/epood/litsents/cancel'
    | '/epood/litsents/success'
    | '/admin/blog'
    | '/admin/clubs'
    | '/admin/dashboard'
    | '/admin/feedback'
    | '/admin/rating'
    | '/admin/tournaments'
    | '/admin/users'
    | '/epood/litsents'
    | '/profile/settings'
    | '/profile/tournaments'
    | '/voistlused/$tournamentid'
    | '/admin/blog/$blogid'
    | '/admin/blog/new'
    | '/admin/rating/$tournamentid'
    | '/admin/tournaments/$tournamentid'
    | '/admin/tournaments/new'
    | '/voistlused/$tournamentid/ajakava'
    | '/voistlused/$tournamentid/galerii'
    | '/voistlused/$tournamentid/juhend'
    | '/voistlused/$tournamentid/kohad'
    | '/voistlused/$tournamentid/lauad'
    | '/voistlused/$tournamentid/mangijad'
    | '/voistlused/$tournamentid/mangud'
    | '/voistlused/$tournamentid/meedia'
    | '/voistlused/$tournamentid/sponsorid'
    | '/voistlused/$tournamentid/tulemused'
    | '/admin/tournaments/$tournamentid/ajakava'
    | '/admin/tournaments/$tournamentid/grupid'
    | '/admin/tournaments/$tournamentid/mangud'
    | '/admin/tournaments/$tournamentid/pildid'
    | '/voistlused/$tournamentid/tulemused/$groupid'
    | '/admin/tournaments/$tournamentid/ajakava/seaded'
    | '/admin/tournaments/$tournamentid/grupid/$groupid'
    | '/admin/tournaments/$tournamentid/grupid/uus'
    | '/admin/tournaments/$tournamentid/grupid/$groupid/kohad'
    | '/admin/tournaments/$tournamentid/grupid/$groupid/mangud'
    | '/admin/tournaments/$tournamentid/grupid/$groupid/osalejad'
    | '/admin/tournaments/$tournamentid/grupid/$groupid/tabelid'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/profile'
    | '/admin/blog'
    | '/admin/clubs'
    | '/admin/dashboard'
    | '/admin/tournaments'
    | '/voistlused/$tournamentid'
    | '/uudised/$blogid'
    | '/klubid/'
    | '/kontakt/'
    | '/login/'
    | '/profile/'
    | '/reeglid/'
    | '/register/'
    | '/reiting/'
    | '/tagasiside/'
    | '/uudised/'
    | '/voistlused/'
    | '/admin/tournaments/$tournamentid'
    | '/epood/litsents/cancel'
    | '/epood/litsents/success'
    | '/admin/blog/'
    | '/admin/clubs/'
    | '/admin/dashboard/'
    | '/admin/feedback/'
    | '/admin/rating/'
    | '/admin/tournaments/'
    | '/admin/users/'
    | '/epood/litsents/'
    | '/profile/settings/'
    | '/profile/tournaments/'
    | '/voistlused/$tournamentid/'
    | '/admin/tournaments/$tournamentid/ajakava'
    | '/admin/blog/$blogid/'
    | '/admin/blog/new/'
    | '/admin/rating/$tournamentid/'
    | '/admin/tournaments/$tournamentid/'
    | '/admin/tournaments/new/'
    | '/voistlused/$tournamentid/ajakava/'
    | '/voistlused/$tournamentid/galerii/'
    | '/voistlused/$tournamentid/juhend/'
    | '/voistlused/$tournamentid/kohad/'
    | '/voistlused/$tournamentid/lauad/'
    | '/voistlused/$tournamentid/mangijad/'
    | '/voistlused/$tournamentid/mangud/'
    | '/voistlused/$tournamentid/meedia/'
    | '/voistlused/$tournamentid/sponsorid/'
    | '/voistlused/$tournamentid/tulemused/'
    | '/admin/tournaments/$tournamentid/grupid/$groupid'
    | '/admin/tournaments/$tournamentid/ajakava/'
    | '/admin/tournaments/$tournamentid/grupid/'
    | '/admin/tournaments/$tournamentid/mangud/'
    | '/admin/tournaments/$tournamentid/pildid/'
    | '/voistlused/$tournamentid/tulemused/$groupid/'
    | '/admin/tournaments/$tournamentid/ajakava/seaded/'
    | '/admin/tournaments/$tournamentid/grupid/$groupid/'
    | '/admin/tournaments/$tournamentid/grupid/uus/'
    | '/admin/tournaments/$tournamentid/grupid/$groupid/kohad/'
    | '/admin/tournaments/$tournamentid/grupid/$groupid/mangud/'
    | '/admin/tournaments/$tournamentid/grupid/$groupid/osalejad/'
    | '/admin/tournaments/$tournamentid/grupid/$groupid/tabelid/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
  ProfileLayoutRoute: typeof ProfileLayoutRouteWithChildren
  VoistlusedTournamentidLayoutRoute: typeof VoistlusedTournamentidLayoutRouteWithChildren
  UudisedBlogidRoute: typeof UudisedBlogidRoute
  KlubidIndexRoute: typeof KlubidIndexRoute
  KontaktIndexRoute: typeof KontaktIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  ReeglidIndexRoute: typeof ReeglidIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
  ReitingIndexRoute: typeof ReitingIndexRoute
  TagasisideIndexRoute: typeof TagasisideIndexRoute
  UudisedIndexRoute: typeof UudisedIndexRoute
  VoistlusedIndexRoute: typeof VoistlusedIndexRoute
  EpoodLitsentsCancelRoute: typeof EpoodLitsentsCancelRoute
  EpoodLitsentsSuccessRoute: typeof EpoodLitsentsSuccessRoute
  EpoodLitsentsIndexRoute: typeof EpoodLitsentsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
  ProfileLayoutRoute: ProfileLayoutRouteWithChildren,
  VoistlusedTournamentidLayoutRoute:
    VoistlusedTournamentidLayoutRouteWithChildren,
  UudisedBlogidRoute: UudisedBlogidRoute,
  KlubidIndexRoute: KlubidIndexRoute,
  KontaktIndexRoute: KontaktIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  ReeglidIndexRoute: ReeglidIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
  ReitingIndexRoute: ReitingIndexRoute,
  TagasisideIndexRoute: TagasisideIndexRoute,
  UudisedIndexRoute: UudisedIndexRoute,
  VoistlusedIndexRoute: VoistlusedIndexRoute,
  EpoodLitsentsCancelRoute: EpoodLitsentsCancelRoute,
  EpoodLitsentsSuccessRoute: EpoodLitsentsSuccessRoute,
  EpoodLitsentsIndexRoute: EpoodLitsentsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/admin",
        "/profile",
        "/voistlused/$tournamentid",
        "/uudised/$blogid",
        "/klubid/",
        "/kontakt/",
        "/login/",
        "/reeglid/",
        "/register/",
        "/reiting/",
        "/tagasiside/",
        "/uudised/",
        "/voistlused/",
        "/epood/litsents/cancel",
        "/epood/litsents/success",
        "/epood/litsents/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/admin": {
      "filePath": "admin/layout.tsx",
      "children": [
        "/admin/blog",
        "/admin/clubs",
        "/admin/dashboard",
        "/admin/tournaments",
        "/admin/feedback/",
        "/admin/rating/",
        "/admin/users/",
        "/admin/rating/$tournamentid/"
      ]
    },
    "/profile": {
      "filePath": "profile/layout.tsx",
      "children": [
        "/profile/",
        "/profile/settings/",
        "/profile/tournaments/"
      ]
    },
    "/admin/blog": {
      "filePath": "admin/blog/layout.tsx",
      "parent": "/admin",
      "children": [
        "/admin/blog/",
        "/admin/blog/$blogid/",
        "/admin/blog/new/"
      ]
    },
    "/admin/clubs": {
      "filePath": "admin/clubs/layout.tsx",
      "parent": "/admin",
      "children": [
        "/admin/clubs/"
      ]
    },
    "/admin/dashboard": {
      "filePath": "admin/dashboard/layout.tsx",
      "parent": "/admin",
      "children": [
        "/admin/dashboard/"
      ]
    },
    "/admin/tournaments": {
      "filePath": "admin/tournaments/layout.tsx",
      "parent": "/admin",
      "children": [
        "/admin/tournaments/$tournamentid",
        "/admin/tournaments/",
        "/admin/tournaments/new/"
      ]
    },
    "/voistlused/$tournamentid": {
      "filePath": "voistlused/$tournamentid/layout.tsx",
      "children": [
        "/voistlused/$tournamentid/",
        "/voistlused/$tournamentid/ajakava/",
        "/voistlused/$tournamentid/galerii/",
        "/voistlused/$tournamentid/juhend/",
        "/voistlused/$tournamentid/kohad/",
        "/voistlused/$tournamentid/lauad/",
        "/voistlused/$tournamentid/mangijad/",
        "/voistlused/$tournamentid/mangud/",
        "/voistlused/$tournamentid/meedia/",
        "/voistlused/$tournamentid/sponsorid/",
        "/voistlused/$tournamentid/tulemused/",
        "/voistlused/$tournamentid/tulemused/$groupid/"
      ]
    },
    "/uudised/$blogid": {
      "filePath": "uudised/$blogid.tsx"
    },
    "/klubid/": {
      "filePath": "klubid/index.tsx"
    },
    "/kontakt/": {
      "filePath": "kontakt/index.tsx"
    },
    "/login/": {
      "filePath": "login/index.tsx"
    },
    "/profile/": {
      "filePath": "profile/index.tsx",
      "parent": "/profile"
    },
    "/reeglid/": {
      "filePath": "reeglid/index.tsx"
    },
    "/register/": {
      "filePath": "register/index.tsx"
    },
    "/reiting/": {
      "filePath": "reiting/index.tsx"
    },
    "/tagasiside/": {
      "filePath": "tagasiside/index.tsx"
    },
    "/uudised/": {
      "filePath": "uudised/index.tsx"
    },
    "/voistlused/": {
      "filePath": "voistlused/index.tsx"
    },
    "/admin/tournaments/$tournamentid": {
      "filePath": "admin/tournaments/$tournamentid/layout.tsx",
      "parent": "/admin/tournaments",
      "children": [
        "/admin/tournaments/$tournamentid/ajakava",
        "/admin/tournaments/$tournamentid/",
        "/admin/tournaments/$tournamentid/grupid/$groupid",
        "/admin/tournaments/$tournamentid/grupid/",
        "/admin/tournaments/$tournamentid/mangud/",
        "/admin/tournaments/$tournamentid/pildid/",
        "/admin/tournaments/$tournamentid/grupid/uus/"
      ]
    },
    "/epood/litsents/cancel": {
      "filePath": "epood/litsents/cancel.tsx"
    },
    "/epood/litsents/success": {
      "filePath": "epood/litsents/success.tsx"
    },
    "/admin/blog/": {
      "filePath": "admin/blog/index.tsx",
      "parent": "/admin/blog"
    },
    "/admin/clubs/": {
      "filePath": "admin/clubs/index.tsx",
      "parent": "/admin/clubs"
    },
    "/admin/dashboard/": {
      "filePath": "admin/dashboard/index.tsx",
      "parent": "/admin/dashboard"
    },
    "/admin/feedback/": {
      "filePath": "admin/feedback/index.tsx",
      "parent": "/admin"
    },
    "/admin/rating/": {
      "filePath": "admin/rating/index.tsx",
      "parent": "/admin"
    },
    "/admin/tournaments/": {
      "filePath": "admin/tournaments/index.tsx",
      "parent": "/admin/tournaments"
    },
    "/admin/users/": {
      "filePath": "admin/users/index.tsx",
      "parent": "/admin"
    },
    "/epood/litsents/": {
      "filePath": "epood/litsents/index.tsx"
    },
    "/profile/settings/": {
      "filePath": "profile/settings/index.tsx",
      "parent": "/profile"
    },
    "/profile/tournaments/": {
      "filePath": "profile/tournaments/index.tsx",
      "parent": "/profile"
    },
    "/voistlused/$tournamentid/": {
      "filePath": "voistlused/$tournamentid/index.tsx",
      "parent": "/voistlused/$tournamentid"
    },
    "/admin/tournaments/$tournamentid/ajakava": {
      "filePath": "admin/tournaments/$tournamentid/ajakava/layout.tsx",
      "parent": "/admin/tournaments/$tournamentid",
      "children": [
        "/admin/tournaments/$tournamentid/ajakava/",
        "/admin/tournaments/$tournamentid/ajakava/seaded/"
      ]
    },
    "/admin/blog/$blogid/": {
      "filePath": "admin/blog/$blogid/index.tsx",
      "parent": "/admin/blog"
    },
    "/admin/blog/new/": {
      "filePath": "admin/blog/new/index.tsx",
      "parent": "/admin/blog"
    },
    "/admin/rating/$tournamentid/": {
      "filePath": "admin/rating/$tournamentid/index.tsx",
      "parent": "/admin"
    },
    "/admin/tournaments/$tournamentid/": {
      "filePath": "admin/tournaments/$tournamentid/index.tsx",
      "parent": "/admin/tournaments/$tournamentid"
    },
    "/admin/tournaments/new/": {
      "filePath": "admin/tournaments/new/index.tsx",
      "parent": "/admin/tournaments"
    },
    "/voistlused/$tournamentid/ajakava/": {
      "filePath": "voistlused/$tournamentid/ajakava/index.tsx",
      "parent": "/voistlused/$tournamentid"
    },
    "/voistlused/$tournamentid/galerii/": {
      "filePath": "voistlused/$tournamentid/galerii/index.tsx",
      "parent": "/voistlused/$tournamentid"
    },
    "/voistlused/$tournamentid/juhend/": {
      "filePath": "voistlused/$tournamentid/juhend/index.tsx",
      "parent": "/voistlused/$tournamentid"
    },
    "/voistlused/$tournamentid/kohad/": {
      "filePath": "voistlused/$tournamentid/kohad/index.tsx",
      "parent": "/voistlused/$tournamentid"
    },
    "/voistlused/$tournamentid/lauad/": {
      "filePath": "voistlused/$tournamentid/lauad/index.tsx",
      "parent": "/voistlused/$tournamentid"
    },
    "/voistlused/$tournamentid/mangijad/": {
      "filePath": "voistlused/$tournamentid/mangijad/index.tsx",
      "parent": "/voistlused/$tournamentid"
    },
    "/voistlused/$tournamentid/mangud/": {
      "filePath": "voistlused/$tournamentid/mangud/index.tsx",
      "parent": "/voistlused/$tournamentid"
    },
    "/voistlused/$tournamentid/meedia/": {
      "filePath": "voistlused/$tournamentid/meedia/index.tsx",
      "parent": "/voistlused/$tournamentid"
    },
    "/voistlused/$tournamentid/sponsorid/": {
      "filePath": "voistlused/$tournamentid/sponsorid/index.tsx",
      "parent": "/voistlused/$tournamentid"
    },
    "/voistlused/$tournamentid/tulemused/": {
      "filePath": "voistlused/$tournamentid/tulemused/index.tsx",
      "parent": "/voistlused/$tournamentid"
    },
    "/admin/tournaments/$tournamentid/grupid/$groupid": {
      "filePath": "admin/tournaments/$tournamentid/grupid/$groupid/layout.tsx",
      "parent": "/admin/tournaments/$tournamentid",
      "children": [
        "/admin/tournaments/$tournamentid/grupid/$groupid/",
        "/admin/tournaments/$tournamentid/grupid/$groupid/kohad/",
        "/admin/tournaments/$tournamentid/grupid/$groupid/mangud/",
        "/admin/tournaments/$tournamentid/grupid/$groupid/osalejad/",
        "/admin/tournaments/$tournamentid/grupid/$groupid/tabelid/"
      ]
    },
    "/admin/tournaments/$tournamentid/ajakava/": {
      "filePath": "admin/tournaments/$tournamentid/ajakava/index.tsx",
      "parent": "/admin/tournaments/$tournamentid/ajakava"
    },
    "/admin/tournaments/$tournamentid/grupid/": {
      "filePath": "admin/tournaments/$tournamentid/grupid/index.tsx",
      "parent": "/admin/tournaments/$tournamentid"
    },
    "/admin/tournaments/$tournamentid/mangud/": {
      "filePath": "admin/tournaments/$tournamentid/mangud/index.tsx",
      "parent": "/admin/tournaments/$tournamentid"
    },
    "/admin/tournaments/$tournamentid/pildid/": {
      "filePath": "admin/tournaments/$tournamentid/pildid/index.tsx",
      "parent": "/admin/tournaments/$tournamentid"
    },
    "/voistlused/$tournamentid/tulemused/$groupid/": {
      "filePath": "voistlused/$tournamentid/tulemused/$groupid/index.tsx",
      "parent": "/voistlused/$tournamentid"
    },
    "/admin/tournaments/$tournamentid/ajakava/seaded/": {
      "filePath": "admin/tournaments/$tournamentid/ajakava/seaded/index.tsx",
      "parent": "/admin/tournaments/$tournamentid/ajakava"
    },
    "/admin/tournaments/$tournamentid/grupid/$groupid/": {
      "filePath": "admin/tournaments/$tournamentid/grupid/$groupid/index.tsx",
      "parent": "/admin/tournaments/$tournamentid/grupid/$groupid"
    },
    "/admin/tournaments/$tournamentid/grupid/uus/": {
      "filePath": "admin/tournaments/$tournamentid/grupid/uus/index.tsx",
      "parent": "/admin/tournaments/$tournamentid"
    },
    "/admin/tournaments/$tournamentid/grupid/$groupid/kohad/": {
      "filePath": "admin/tournaments/$tournamentid/grupid/$groupid/kohad/index.tsx",
      "parent": "/admin/tournaments/$tournamentid/grupid/$groupid"
    },
    "/admin/tournaments/$tournamentid/grupid/$groupid/mangud/": {
      "filePath": "admin/tournaments/$tournamentid/grupid/$groupid/mangud/index.tsx",
      "parent": "/admin/tournaments/$tournamentid/grupid/$groupid"
    },
    "/admin/tournaments/$tournamentid/grupid/$groupid/osalejad/": {
      "filePath": "admin/tournaments/$tournamentid/grupid/$groupid/osalejad/index.tsx",
      "parent": "/admin/tournaments/$tournamentid/grupid/$groupid"
    },
    "/admin/tournaments/$tournamentid/grupid/$groupid/tabelid/": {
      "filePath": "admin/tournaments/$tournamentid/grupid/$groupid/tabelid/index.tsx",
      "parent": "/admin/tournaments/$tournamentid/grupid/$groupid"
    }
  }
}
ROUTE_MANIFEST_END */
